package me.ifydev.core.spigot.items;

import lombok.Getter;
import org.bukkit.Material;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * @author Innectic
 * @since 10/5/2017
 */
public class BlockRegistry {
    @Getter private static List<BaseItem> registeredBlocks = new ArrayList<>();

    private static boolean setup = false;

    public static void setup() {
        if (setup) return;
        setup = true;

        registeredBlocks.add(new BaseItem("Air", Material.AIR));
        registeredBlocks.add(new BaseItem("Stone", Material.STONE));
        registeredBlocks.add(new BaseItem("Granite", Material.STONE, 1));
        registeredBlocks.add(new BaseItem("Polished Granite", Material.STONE, 2));
        registeredBlocks.add(new BaseItem("Diorite", Material.STONE, 3));
        registeredBlocks.add(new BaseItem("Polished Diorite", Material.STONE, 4));
        registeredBlocks.add(new BaseItem("Andesite", Material.STONE, 5));
        registeredBlocks.add(new BaseItem("Polished Andesite", Material.STONE, 6));
        registeredBlocks.add(new BaseItem("Grass", Material.GRASS));
        registeredBlocks.add(new BaseItem("Dirt", Material.DIRT));
        registeredBlocks.add(new BaseItem("Coarse Dirt", Material.DIRT, 1));
        registeredBlocks.add(new BaseItem("Podzol", Material.DIRT, 2));
        registeredBlocks.add(new BaseItem("Cobblestone", Material.COBBLESTONE));
        registeredBlocks.add(new BaseItem("Oak Plank", Material.WOOD));
        registeredBlocks.add(new BaseItem("Spruce Plank", Material.WOOD, 1));
        registeredBlocks.add(new BaseItem("Birch Plank", Material.WOOD, 2));
        registeredBlocks.add(new BaseItem("Jungle Plank", Material.WOOD, 3));
        registeredBlocks.add(new BaseItem("Acacia Plank", Material.WOOD, 4));
        registeredBlocks.add(new BaseItem("Dark Oak Plank", Material.WOOD, 5));
        registeredBlocks.add(new BaseItem("Oak Sapling", Material.SAPLING));
        registeredBlocks.add(new BaseItem("Spruce Sapling", Material.SAPLING, 1));
        registeredBlocks.add(new BaseItem("Birch Sapling", Material.SAPLING, 2));
        registeredBlocks.add(new BaseItem("Jungle Sapling", Material.SAPLING, 3));
        registeredBlocks.add(new BaseItem("Acacia Sapling", Material.SAPLING, 4));
        registeredBlocks.add(new BaseItem("Dark Oak Sapling", Material.SAPLING, 5));
        registeredBlocks.add(new BaseItem("Bedrock", Material.BEDROCK));
        registeredBlocks.add(new BaseItem("Sand", Material.SAND));
        registeredBlocks.add(new BaseItem("Red Sand", Material.SAND, 1));
        registeredBlocks.add(new BaseItem("Gravel", Material.GRAVEL));
        registeredBlocks.add(new BaseItem("Gold Ore", Material.GOLD_ORE));
        registeredBlocks.add(new BaseItem("Iron Ore", Material.IRON_ORE));
        registeredBlocks.add(new BaseItem("Coal Ore", Material.COAL_ORE));
        registeredBlocks.add(new BaseItem("Lapis Lazuli Ore", Material.LAPIS_ORE));
        registeredBlocks.add(new BaseItem("Oak Log", Material.LOG));
        registeredBlocks.add(new BaseItem("Spruce Log", Material.LOG, 1));
        registeredBlocks.add(new BaseItem("Birch Log", Material.LOG, 2));
        registeredBlocks.add(new BaseItem("Jungle Log", Material.LOG, 3));
        registeredBlocks.add(new BaseItem("Oak Leaves", Material.LEAVES));
        registeredBlocks.add(new BaseItem("Spruce Leaves", Material.LEAVES, 1));
        registeredBlocks.add(new BaseItem("Birch Leaves", Material.LEAVES, 2));
        registeredBlocks.add(new BaseItem("Jungle Leaves", Material.LEAVES, 3));
        registeredBlocks.add(new BaseItem("Sponge", Material.SPONGE));
        registeredBlocks.add(new BaseItem("Wet Sponge", Material.SPONGE, 1));
        registeredBlocks.add(new BaseItem("Glass", Material.GLASS));
        registeredBlocks.add(new BaseItem("Lapis Lazuli Block", Material.LAPIS_BLOCK));
        registeredBlocks.add(new BaseItem("Dispenser", Material.DISPENSER));
        registeredBlocks.add(new BaseItem("Sandstone", Material.SANDSTONE));
        registeredBlocks.add(new BaseItem("Chiseled Sandstone", Material.SANDSTONE, 1));
        registeredBlocks.add(new BaseItem("Smooth Sandstone", Material.SANDSTONE, 2));
        registeredBlocks.add(new BaseItem("Note Block", Material.NOTE_BLOCK));
        registeredBlocks.add(new BaseItem("Bed", Material.BED));
        registeredBlocks.add(new BaseItem("Powered Rail", Material.POWERED_RAIL));
        registeredBlocks.add(new BaseItem("Detector Rail", Material.DETECTOR_RAIL));
        registeredBlocks.add(new BaseItem("Piston", Material.PISTON_BASE));
        registeredBlocks.add(new BaseItem("Sticky Piston", Material.PISTON_STICKY_BASE));
        registeredBlocks.add(new BaseItem("Cobweb", Material.WEB));
        registeredBlocks.add(new BaseItem("Dead Shrub", Material.DEAD_BUSH));
        registeredBlocks.add(new BaseItem("Tall Grass", Material.DEAD_BUSH, 1));
        registeredBlocks.add(new BaseItem("Fern", Material.DEAD_BUSH, 2));
        // TODO: dead bush / dead shrug what in tarnation?
        registeredBlocks.add(new BaseItem("White Wool", Material.WOOL));
        registeredBlocks.add(new BaseItem("Orange Wool", Material.WOOL, 1));
        registeredBlocks.add(new BaseItem("Magenta Wool", Material.WOOL, 2));
        registeredBlocks.add(new BaseItem("Light Blue Wool", Material.WOOL, 3));
        registeredBlocks.add(new BaseItem("Yellow Wool", Material.WOOL, 4));
        registeredBlocks.add(new BaseItem("Lime Wool", Material.WOOL, 5));
        registeredBlocks.add(new BaseItem("Pink Wool", Material.WOOL, 6));
        registeredBlocks.add(new BaseItem("Gray Wool", Material.WOOL, 7));
        registeredBlocks.add(new BaseItem("Light Gray Wool", Material.WOOL, 8));
        registeredBlocks.add(new BaseItem("Cyan Wool", Material.WOOL, 9));
        registeredBlocks.add(new BaseItem("Purple Wool", Material.WOOL, 10));
        registeredBlocks.add(new BaseItem("Blue Wool", Material.WOOL, 11));
        registeredBlocks.add(new BaseItem("Brown Wool", Material.WOOL, 12));
        registeredBlocks.add(new BaseItem("Green Wool", Material.WOOL, 13));
        registeredBlocks.add(new BaseItem("Red Wool", Material.WOOL, 14));
        registeredBlocks.add(new BaseItem("Black Wool", Material.WOOL, 15));
        registeredBlocks.add(new BaseItem("Dandelion", Material.YELLOW_FLOWER));
        registeredBlocks.add(new BaseItem("Poppy", Material.RED_ROSE));
        registeredBlocks.add(new BaseItem("Blue Orchid", Material.RED_ROSE, 1));
        registeredBlocks.add(new BaseItem("Allium", Material.RED_ROSE, 2));
        registeredBlocks.add(new BaseItem("Azure Bluet", Material.RED_ROSE, 3));
        registeredBlocks.add(new BaseItem("Red Tulip", Material.RED_ROSE, 4));
        registeredBlocks.add(new BaseItem("Orange Tulip", Material.RED_ROSE, 5));
        registeredBlocks.add(new BaseItem("White Tulip", Material.RED_ROSE, 6));
        registeredBlocks.add(new BaseItem("Pink Tulip", Material.RED_ROSE, 7));
        registeredBlocks.add(new BaseItem("Oxeye Daisy", Material.RED_ROSE, 8));
        registeredBlocks.add(new BaseItem("Brown Mushroom", Material.BROWN_MUSHROOM));
        registeredBlocks.add(new BaseItem("Red Mushroom", Material.RED_MUSHROOM));
        registeredBlocks.add(new BaseItem("Gold Block", Material.GOLD_BLOCK));
        registeredBlocks.add(new BaseItem("Iron Block", Material.IRON_BLOCK));
        registeredBlocks.add(new BaseItem("Stone Slab", Material.STEP));
        registeredBlocks.add(new BaseItem("Sandstone Slab", Material.STEP, 1));
        registeredBlocks.add(new BaseItem("Wooden Slab", Material.STEP, 2));
        registeredBlocks.add(new BaseItem("Cobblestone Slab", Material.STEP, 3));
        registeredBlocks.add(new BaseItem("Brick Slab", Material.STEP, 4));
        registeredBlocks.add(new BaseItem("Stone Brick Slab", Material.STEP, 5));
        registeredBlocks.add(new BaseItem("Nether Brick Slab", Material.STEP, 6));
        registeredBlocks.add(new BaseItem("Quartz Slab", Material.STEP, 7));
        registeredBlocks.add(new BaseItem("Bricks", Material.BRICK));
        registeredBlocks.add(new BaseItem("TNT", Material.TNT));
        registeredBlocks.add(new BaseItem("Bookshelf", Material.BOOKSHELF));
        registeredBlocks.add(new BaseItem("Mossy Cobblestone", Material.MOSSY_COBBLESTONE));
        registeredBlocks.add(new BaseItem("Obsidian", Material.OBSIDIAN));
        registeredBlocks.add(new BaseItem("Torch", Material.TORCH));
        registeredBlocks.add(new BaseItem("Oak Stairs", Material.WOOD_STAIRS));
        registeredBlocks.add(new BaseItem("Chest", Material.CHEST));
        registeredBlocks.add(new BaseItem("Diamond Ore", Material.DIAMOND_ORE));
        registeredBlocks.add(new BaseItem("Crafting Table", Material.WORKBENCH));
        registeredBlocks.add(new BaseItem("Farmland", Material.SOIL));
        registeredBlocks.add(new BaseItem("Furnace", Material.FURNACE));
        registeredBlocks.add(new BaseItem("Sign", Material.SIGN));
        registeredBlocks.add(new BaseItem("Oak Door", Material.WOOD_DOOR));
        registeredBlocks.add(new BaseItem("Ladder", Material.LADDER));
        registeredBlocks.add(new BaseItem("Rail", Material.RAILS));
        registeredBlocks.add(new BaseItem("Cobblestone Stairs", Material.COBBLESTONE_STAIRS));
        registeredBlocks.add(new BaseItem("Lever", Material.LEVER));
        registeredBlocks.add(new BaseItem("Stone Pressure Plate", Material.STONE_PLATE));
        registeredBlocks.add(new BaseItem("Wooden Pressure Plate", Material.WOOD_PLATE));
        registeredBlocks.add(new BaseItem("Redstone Ore", Material.REDSTONE_ORE));
        registeredBlocks.add(new BaseItem("Redstone Torch", Material.REDSTONE_TORCH_OFF));
        registeredBlocks.add(new BaseItem("Stone Button", Material.STONE_BUTTON));
        registeredBlocks.add(new BaseItem("Snow", Material.SNOW));
        registeredBlocks.add(new BaseItem("Ice", Material.ICE));
        registeredBlocks.add(new BaseItem("Snow Block", Material.SNOW_BLOCK));
        registeredBlocks.add(new BaseItem("Cactus", Material.CACTUS));
        registeredBlocks.add(new BaseItem("Clay Block", Material.CLAY));
        registeredBlocks.add(new BaseItem("Sugar Cane", Material.SUGAR_CANE));
        registeredBlocks.add(new BaseItem("Jukebox", Material.JUKEBOX));
        registeredBlocks.add(new BaseItem("Oak Fence", Material.FENCE));
        registeredBlocks.add(new BaseItem("Pumpkin", Material.PUMPKIN));
        registeredBlocks.add(new BaseItem("Netherrack", Material.NETHERRACK));
        registeredBlocks.add(new BaseItem("Soul Sand", Material.SOUL_SAND));
        registeredBlocks.add(new BaseItem("Glowstone", Material.GLOWSTONE));
        registeredBlocks.add(new BaseItem("Jack-O-Lantern", Material.JACK_O_LANTERN));
        registeredBlocks.add(new BaseItem("Cake", Material.CAKE));
        registeredBlocks.add(new BaseItem("Redstone Repeater", Material.DIODE_BLOCK_OFF));
        registeredBlocks.add(new BaseItem("White Stained Glass", Material.STAINED_GLASS));
        registeredBlocks.add(new BaseItem("Orange Stained Glass", Material.STAINED_GLASS, 1));
        registeredBlocks.add(new BaseItem("Magenta Stained Glass", Material.STAINED_GLASS, 2));
        registeredBlocks.add(new BaseItem("Light Blue Stained Glass", Material.STAINED_GLASS, 3));
        registeredBlocks.add(new BaseItem("Yellow Stained Glass", Material.STAINED_GLASS, 4));
        registeredBlocks.add(new BaseItem("Lime Stained Glass", Material.STAINED_GLASS, 5));
        registeredBlocks.add(new BaseItem("Pink Stained Glass", Material.STAINED_GLASS, 6));
        registeredBlocks.add(new BaseItem("Gray Stained Glass", Material.STAINED_GLASS, 7));
        registeredBlocks.add(new BaseItem("Light Gray Stained Glass", Material.STAINED_GLASS, 8));
        registeredBlocks.add(new BaseItem("Cyan Stained Glass", Material.STAINED_GLASS, 9));
        registeredBlocks.add(new BaseItem("Purple Stained Glass", Material.STAINED_GLASS, 10));
        registeredBlocks.add(new BaseItem("Blue Stained Glass", Material.STAINED_GLASS, 11));
        registeredBlocks.add(new BaseItem("Brown Stained Glass", Material.STAINED_GLASS, 12));
        registeredBlocks.add(new BaseItem("Green Stained Glass", Material.STAINED_GLASS, 13));
        registeredBlocks.add(new BaseItem("Red Stained Glass", Material.STAINED_GLASS, 14));
        registeredBlocks.add(new BaseItem("Black Stained Glass", Material.STAINED_GLASS, 15));
        registeredBlocks.add(new BaseItem("Stone Monster Egg", Material.MONSTER_EGGS));
        registeredBlocks.add(new BaseItem("Cobblestone Monster Egg", Material.MONSTER_EGGS, 1));
        registeredBlocks.add(new BaseItem("Stone Brick Monster Egg", Material.MONSTER_EGGS, 2));
        registeredBlocks.add(new BaseItem("Mossy Stone Brick Monster Egg", Material.MONSTER_EGGS, 3));
        registeredBlocks.add(new BaseItem("Cracked Stone Brick Monster Egg", Material.MONSTER_EGGS, 4));
        registeredBlocks.add(new BaseItem("Stone Brick", Material.SMOOTH_BRICK));
        registeredBlocks.add(new BaseItem("Mossy Stone Brick", Material.SMOOTH_BRICK, 1));
        registeredBlocks.add(new BaseItem("Cracked Stone Brick", Material.SMOOTH_BRICK, 2));
        registeredBlocks.add(new BaseItem("Chiseled Stone Brick", Material.SMOOTH_BRICK, 3));
        registeredBlocks.add(new BaseItem("Brown Mushroom Block", Material.HUGE_MUSHROOM_1));
        registeredBlocks.add(new BaseItem("Red Mushroom Block", Material.HUGE_MUSHROOM_2));
        registeredBlocks.add(new BaseItem("Iron Bars", Material.IRON_BARDING));
        registeredBlocks.add(new BaseItem("Glass Pane", Material.THIN_GLASS));
        registeredBlocks.add(new BaseItem("Melon Block", Material.MELON_BLOCK));
        registeredBlocks.add(new BaseItem("Vines", Material.VINE));
        registeredBlocks.add(new BaseItem("Oak Fence Gate", Material.FENCE_GATE));
        registeredBlocks.add(new BaseItem("Brick Stairs", Material.BRICK_STAIRS));
        registeredBlocks.add(new BaseItem("Stone Brick Stairs", Material.SMOOTH_STAIRS));
        registeredBlocks.add(new BaseItem("Mycelium", Material.MYCEL));
        registeredBlocks.add(new BaseItem("Lily Pad", Material.WATER_LILY));
        registeredBlocks.add(new BaseItem("Nether Brick", Material.NETHER_BRICK));
        registeredBlocks.add(new BaseItem("Nether Brick Fence", Material.NETHER_FENCE));
        registeredBlocks.add(new BaseItem("Nether Brick Stairs", Material.NETHER_BRICK_STAIRS));
        registeredBlocks.add(new BaseItem("Nether Wart", Material.NETHER_WARTS));
        registeredBlocks.add(new BaseItem("Enchantment Table", Material.ENCHANTMENT_TABLE));
        registeredBlocks.add(new BaseItem("Brewing Stand", Material.BREWING_STAND));
        registeredBlocks.add(new BaseItem("Cauldron", Material.CAULDRON));
        registeredBlocks.add(new BaseItem("End Portal Frame", Material.ENDER_PORTAL_FRAME));
        registeredBlocks.add(new BaseItem("End Stone", Material.ENDER_STONE));
        registeredBlocks.add(new BaseItem("Dragon Egg", Material.DRAGON_EGG));
        registeredBlocks.add(new BaseItem("Redstone Lamp", Material.REDSTONE_LAMP_OFF));
        registeredBlocks.add(new BaseItem("Oak Slab", Material.WOOD_STEP));
        registeredBlocks.add(new BaseItem("Spruce Slab", Material.WOOD_STEP, 1));
        registeredBlocks.add(new BaseItem("Birch Slab", Material.WOOD_STEP, 2));
        registeredBlocks.add(new BaseItem("Jungle Slab", Material.WOOD_STEP, 3));
        registeredBlocks.add(new BaseItem("Acacia Slab", Material.WOOD_STEP, 4));
        registeredBlocks.add(new BaseItem("Dark Oak Slab", Material.WOOD_STEP, 5));
        registeredBlocks.add(new BaseItem("Sandstone Stairs", Material.SANDSTONE_STAIRS));
        registeredBlocks.add(new BaseItem("Emerald Ore", Material.EMERALD_ORE));
        registeredBlocks.add(new BaseItem("Ender Chest", Material.ENDER_CHEST));
        registeredBlocks.add(new BaseItem("Tripwire Hook", Material.TRIPWIRE_HOOK));
        registeredBlocks.add(new BaseItem("Emerald Block", Material.EMERALD_BLOCK));
        registeredBlocks.add(new BaseItem("Spruce Stairs", Material.SPRUCE_WOOD_STAIRS));
        registeredBlocks.add(new BaseItem("Jungle Stairs", Material.JUNGLE_WOOD_STAIRS));
        registeredBlocks.add(new BaseItem("Command Block", Material.COMMAND));
        registeredBlocks.add(new BaseItem("Beacon", Material.BEACON));
        registeredBlocks.add(new BaseItem("Cobblestone Wall", Material.COBBLE_WALL));
        registeredBlocks.add(new BaseItem("Mossy Cobblestone Wall", Material.COBBLE_WALL, 1));
        registeredBlocks.add(new BaseItem("Flower Pot", Material.FLOWER_POT));
        registeredBlocks.add(new BaseItem("Wood Button", Material.WOOD_BUTTON));
        registeredBlocks.add(new BaseItem("Skeleton Skull", Material.SKULL_ITEM));
        registeredBlocks.add(new BaseItem("Anvil", Material.ANVIL));
        registeredBlocks.add(new BaseItem("Trapped Chest", Material.TRAPPED_CHEST));
        registeredBlocks.add(new BaseItem("Weighted Iron Plate", Material.IRON_PLATE));
        registeredBlocks.add(new BaseItem("Weighted Gold Plate", Material.GOLD_PLATE));
        registeredBlocks.add(new BaseItem("Comparator", Material.REDSTONE_COMPARATOR_OFF));
        registeredBlocks.add(new BaseItem("Daylight Sensor", Material.DAYLIGHT_DETECTOR));
        registeredBlocks.add(new BaseItem("Redstone Block", Material.REDSTONE_BLOCK));
        registeredBlocks.add(new BaseItem("Nether Quartz Ore", Material.QUARTZ_ORE));
        registeredBlocks.add(new BaseItem("Hopper", Material.HOPPER));
        registeredBlocks.add(new BaseItem("Quartz Block", Material.QUARTZ_BLOCK));
        registeredBlocks.add(new BaseItem("Chiseled Quartz Block", Material.QUARTZ_BLOCK, 1));
        registeredBlocks.add(new BaseItem("Pillar Quartz Block", Material.QUARTZ_BLOCK, 2));
        registeredBlocks.add(new BaseItem("Activator Rail", Material.ACTIVATOR_RAIL));
        registeredBlocks.add(new BaseItem("Dropper", Material.DROPPER));
        registeredBlocks.add(new BaseItem("White Stained Clay", Material.STAINED_CLAY));
        registeredBlocks.add(new BaseItem("Orange Stained Clay", Material.STAINED_CLAY, 1));
        registeredBlocks.add(new BaseItem("Magenta Stained Clay", Material.STAINED_CLAY, 2));
        registeredBlocks.add(new BaseItem("Light Blue Stained Clay", Material.STAINED_CLAY, 3));
        registeredBlocks.add(new BaseItem("Yellow Stained Clay", Material.STAINED_CLAY, 4));
        registeredBlocks.add(new BaseItem("Lime Stained Clay", Material.STAINED_CLAY, 5));
        registeredBlocks.add(new BaseItem("Pink Stained Clay", Material.STAINED_CLAY, 6));
        registeredBlocks.add(new BaseItem("Gray Stained Clay", Material.STAINED_CLAY, 7));
        registeredBlocks.add(new BaseItem("Light Gray Stained Clay", Material.STAINED_CLAY, 8));
        registeredBlocks.add(new BaseItem("Cyan Stained Clay", Material.STAINED_CLAY, 9));
        registeredBlocks.add(new BaseItem("Purple Stained Clay", Material.STAINED_CLAY, 10));
        registeredBlocks.add(new BaseItem("Blue Stained Clay", Material.STAINED_CLAY, 11));
        registeredBlocks.add(new BaseItem("Brown Stained Clay", Material.STAINED_CLAY, 12));
        registeredBlocks.add(new BaseItem("Green Stained Clay", Material.STAINED_CLAY, 13));
        registeredBlocks.add(new BaseItem("Red Stained Clay", Material.STAINED_CLAY, 14));
        registeredBlocks.add(new BaseItem("Black Stained Clay", Material.STAINED_CLAY, 15));
        registeredBlocks.add(new BaseItem("White Stained Glass Pane", Material.STAINED_GLASS_PANE));
        registeredBlocks.add(new BaseItem("Orange Stained Glass Pane", Material.STAINED_GLASS_PANE, 1));
        registeredBlocks.add(new BaseItem("Magenta Stained Glass Pane", Material.STAINED_GLASS_PANE, 2));
        registeredBlocks.add(new BaseItem("Light Blue Stained Glass Pane", Material.STAINED_GLASS_PANE, 3));
        registeredBlocks.add(new BaseItem("Yellow Stained Glass Pane", Material.STAINED_GLASS_PANE, 4));
        registeredBlocks.add(new BaseItem("Lime Stained Glass Pane", Material.STAINED_GLASS_PANE, 5));
        registeredBlocks.add(new BaseItem("Pink Stained Glass Pane", Material.STAINED_GLASS_PANE, 6));
        registeredBlocks.add(new BaseItem("Gray Stained Glass Pane", Material.STAINED_GLASS_PANE, 7));
        registeredBlocks.add(new BaseItem("Light Gray Stained Glass Pane", Material.STAINED_GLASS_PANE, 8));
        registeredBlocks.add(new BaseItem("Cyan Stained Glass Pane", Material.STAINED_GLASS_PANE, 9));
        registeredBlocks.add(new BaseItem("Purple Stained Glass Pane", Material.STAINED_GLASS_PANE, 10));
        registeredBlocks.add(new BaseItem("Blue Stained Glass Pane", Material.STAINED_GLASS_PANE, 11));
        registeredBlocks.add(new BaseItem("Brown Stained Glass Pane", Material.STAINED_GLASS_PANE, 12));
        registeredBlocks.add(new BaseItem("Green Stained Glass Pane", Material.STAINED_GLASS_PANE, 13));
        registeredBlocks.add(new BaseItem("Red Stained Glass Pane", Material.STAINED_GLASS_PANE, 14));
        registeredBlocks.add(new BaseItem("Black Stained Glass Pane", Material.STAINED_GLASS_PANE, 15));
        registeredBlocks.add(new BaseItem("Acacia Leaves", Material.LEAVES_2));
        registeredBlocks.add(new BaseItem("Dark Oak Leaves", Material.LEAVES_2, 1));
        registeredBlocks.add(new BaseItem("Acacia Wood", Material.LOG_2));
        registeredBlocks.add(new BaseItem("Dark Oak Log", Material.LOG_2, 1));
        registeredBlocks.add(new BaseItem("Slime Block", Material.SLIME_BLOCK));
        registeredBlocks.add(new BaseItem("Barrier", Material.BARRIER));
        registeredBlocks.add(new BaseItem("Iron Trapdoor", Material.IRON_TRAPDOOR));
        registeredBlocks.add(new BaseItem("Prismarine", Material.PRISMARINE));
        registeredBlocks.add(new BaseItem("Prismarine Bricks", Material.PRISMARINE, 1));
        registeredBlocks.add(new BaseItem("Dark Prismarine", Material.PRISMARINE, 2));
        registeredBlocks.add(new BaseItem("Sea Lantern", Material.SEA_LANTERN));
        registeredBlocks.add(new BaseItem("Hay Bale", Material.HAY_BLOCK));
        registeredBlocks.add(new BaseItem("White Carpet", Material.CARPET));
        registeredBlocks.add(new BaseItem("Orange Carpet", Material.CARPET, 1));
        registeredBlocks.add(new BaseItem("Magenta Carpet", Material.CARPET, 2));
        registeredBlocks.add(new BaseItem("Light Blue Carpet", Material.CARPET, 3));
        registeredBlocks.add(new BaseItem("Yellow Carpet", Material.CARPET, 4));
        registeredBlocks.add(new BaseItem("Lime Carpet", Material.CARPET, 5));
        registeredBlocks.add(new BaseItem("Pink Carpet", Material.CARPET, 6));
        registeredBlocks.add(new BaseItem("Gray Carpet", Material.CARPET, 7));
        registeredBlocks.add(new BaseItem("Light Gray Carpet", Material.CARPET, 8));
        registeredBlocks.add(new BaseItem("Cyan Carpet", Material.CARPET, 9));
        registeredBlocks.add(new BaseItem("Purple Carpet", Material.CARPET, 10));
        registeredBlocks.add(new BaseItem("Blue Carpet", Material.CARPET, 11));
        registeredBlocks.add(new BaseItem("Brown Carpet", Material.CARPET, 12));
        registeredBlocks.add(new BaseItem("Green Carpet", Material.CARPET, 13));
        registeredBlocks.add(new BaseItem("Red Carpet", Material.CARPET, 14));
        registeredBlocks.add(new BaseItem("Black Carpet", Material.CARPET, 15));
        registeredBlocks.add(new BaseItem("Hardened Clay", Material.HARD_CLAY));
        registeredBlocks.add(new BaseItem("Coal Block", Material.COAL_BLOCK));
        registeredBlocks.add(new BaseItem("Packed Ice", Material.PACKED_ICE));
        registeredBlocks.add(new BaseItem("Sun Flower", Material.DOUBLE_PLANT));
        registeredBlocks.add(new BaseItem("Lilac", Material.DOUBLE_PLANT, 1));
        registeredBlocks.add(new BaseItem("Double Tall Grass", Material.DOUBLE_PLANT, 2));
        registeredBlocks.add(new BaseItem("Tall Fern", Material.DOUBLE_PLANT, 3));
        registeredBlocks.add(new BaseItem("Rose Bush", Material.DOUBLE_PLANT, 4));
        registeredBlocks.add(new BaseItem("Peony", Material.DOUBLE_PLANT, 5));
        registeredBlocks.add(new BaseItem("Red Sandstone", Material.RED_SANDSTONE));
        registeredBlocks.add(new BaseItem("Chiseled Red Sandstone", Material.RED_SANDSTONE, 1));
        registeredBlocks.add(new BaseItem("Smooth Red Sandstone", Material.RED_SANDSTONE, 2));
        registeredBlocks.add(new BaseItem("Red Sandstone Stairs", Material.RED_SANDSTONE_STAIRS));
        registeredBlocks.add(new BaseItem("Red Sandstone Slab", Material.STONE_SLAB2));
        registeredBlocks.add(new BaseItem("Spruce Gate", Material.SPRUCE_FENCE_GATE));
        registeredBlocks.add(new BaseItem("Birch Gate", Material.BIRCH_FENCE_GATE));
        registeredBlocks.add(new BaseItem("Jungle Gate", Material.JUNGLE_FENCE_GATE));
        registeredBlocks.add(new BaseItem("Dark Oak Gate", Material.DARK_OAK_FENCE_GATE));
        registeredBlocks.add(new BaseItem("Acacia Gate", Material.ACACIA_FENCE_GATE));
        registeredBlocks.add(new BaseItem("Spruce Fence", Material.SPRUCE_FENCE));
        registeredBlocks.add(new BaseItem("Birch Fence", Material.BIRCH_FENCE));
        registeredBlocks.add(new BaseItem("Jungle Fence", Material.JUNGLE_FENCE));
        registeredBlocks.add(new BaseItem("Dark Oak Fence", Material.DARK_OAK_FENCE));
        registeredBlocks.add(new BaseItem("Acacia Fence", Material.ACACIA_FENCE));
        registeredBlocks.add(new BaseItem("Spruce Door", Material.SPRUCE_DOOR));
        registeredBlocks.add(new BaseItem("Birch Door", Material.BIRCH_DOOR));
        registeredBlocks.add(new BaseItem("Jungle Door", Material.JUNGLE_DOOR));
        registeredBlocks.add(new BaseItem("Acacia Door", Material.ACACIA_DOOR));
        registeredBlocks.add(new BaseItem("Dark Oak Door", Material.DARK_OAK_DOOR));
        registeredBlocks.add(new BaseItem("End Rod", Material.END_ROD));
        registeredBlocks.add(new BaseItem("Chorus Plant", Material.CHORUS_PLANT));
        registeredBlocks.add(new BaseItem("Chorus Flower", Material.CHORUS_FLOWER));
        registeredBlocks.add(new BaseItem("Purpur Block", Material.PURPUR_BLOCK));
        registeredBlocks.add(new BaseItem("Purpur Pillar", Material.PURPUR_PILLAR));
        registeredBlocks.add(new BaseItem("Purpur Stairs", Material.PURPUR_STAIRS));
        registeredBlocks.add(new BaseItem("Purpur Slab", Material.PURPUR_SLAB));
        registeredBlocks.add(new BaseItem("End Stone Brick", Material.END_BRICKS));
        registeredBlocks.add(new BaseItem("Grass Path", Material.GRASS_PATH));
        registeredBlocks.add(new BaseItem("Repeating Command Block", Material.COMMAND_REPEATING));
        registeredBlocks.add(new BaseItem("Chain Command Block", Material.COMMAND_CHAIN));
        registeredBlocks.add(new BaseItem("Magma Block", Material.MAGMA));
        registeredBlocks.add(new BaseItem("Nether Wart Block", Material.NETHER_WART_BLOCK));
        registeredBlocks.add(new BaseItem("Red Nether Brick", Material.RED_NETHER_BRICK));
        registeredBlocks.add(new BaseItem("Bone Block", Material.BONE_BLOCK));
        registeredBlocks.add(new BaseItem("Structure Void", Material.STRUCTURE_VOID));
        registeredBlocks.add(new BaseItem("Observer", Material.OBSERVER));
        registeredBlocks.add(new BaseItem("White Shulker Box", Material.WHITE_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Orange Shulker Box", Material.ORANGE_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Magenta Shulker Box", Material.MAGENTA_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Light Blue Shulker Box", Material.LIGHT_BLUE_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Yellow Shulker Box", Material.YELLOW_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Lime Shulker Box", Material.LIME_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Pink Shulker Box", Material.PINK_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Gray Shulker Box", Material.GRAY_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Light Gray Shulker Box", Material.SILVER_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Cyan Shulker Box", Material.CYAN_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Purple Shulker Box", Material.PURPLE_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Blue Shulker Box", Material.BLUE_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Brown Shulker Box", Material.BROWN_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Green Shulker Box", Material.GREEN_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Red Shulker Box", Material.RED_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("Black Shulker Box", Material.BLACK_SHULKER_BOX));
        registeredBlocks.add(new BaseItem("White Glazed Terracotta", Material.WHITE_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Orange Glazed Terracotta", Material.ORANGE_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Magenta Glazed Terracotta", Material.MAGENTA_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Light Blue Glazed Terracotta", Material.LIGHT_BLUE_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Yellow Glazed Terracotta", Material.YELLOW_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Lime Glazed Terracotta", Material.LIME_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Pink Glazed Terracotta", Material.PINK_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Gray Glazed Terracotta", Material.GRAY_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Light Gray Glazed Terracotta", Material.SILVER_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Cyan Glazed Terracotta", Material.CYAN_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Purple Glazed Terracotta", Material.PURPLE_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Blue Glazed Terracotta", Material.BLUE_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Brown Glazed Terracotta", Material.BROWN_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Green Glazed Terracotta", Material.GREEN_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Red Glazed Terracotta", Material.RED_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("Black Glazed Terracotta", Material.BLACK_GLAZED_TERRACOTTA));
        registeredBlocks.add(new BaseItem("White Concrete", Material.CONCRETE));
        registeredBlocks.add(new BaseItem("Orange Concrete", Material.CONCRETE, 1));
        registeredBlocks.add(new BaseItem("Magenta Concrete", Material.CONCRETE, 2));
        registeredBlocks.add(new BaseItem("Light Blue Concrete", Material.CONCRETE, 3));
        registeredBlocks.add(new BaseItem("Yellow Concrete", Material.CONCRETE, 4));
        registeredBlocks.add(new BaseItem("Lime Concrete", Material.CONCRETE, 5));
        registeredBlocks.add(new BaseItem("Pink Concrete", Material.CONCRETE, 6));
        registeredBlocks.add(new BaseItem("Gray Concrete", Material.CONCRETE, 7));
        registeredBlocks.add(new BaseItem("Light Gray Concrete", Material.CONCRETE, 8));
        registeredBlocks.add(new BaseItem("Cyan Concrete", Material.CONCRETE, 9));
        registeredBlocks.add(new BaseItem("Purple Concrete", Material.CONCRETE, 10));
        registeredBlocks.add(new BaseItem("Blue Concrete", Material.CONCRETE, 11));
        registeredBlocks.add(new BaseItem("Brown Concrete", Material.CONCRETE, 12));
        registeredBlocks.add(new BaseItem("Green Concrete", Material.CONCRETE, 13));
        registeredBlocks.add(new BaseItem("Red Concrete", Material.CONCRETE, 14));
        registeredBlocks.add(new BaseItem("Black Concrete", Material.CONCRETE, 15));
        registeredBlocks.add(new BaseItem("White Concrete Powder", Material.CONCRETE_POWDER));
        registeredBlocks.add(new BaseItem("Orange Concrete Powder", Material.CONCRETE_POWDER, 1));
        registeredBlocks.add(new BaseItem("Magenta Concrete Powder", Material.CONCRETE_POWDER, 2));
        registeredBlocks.add(new BaseItem("Light Blue Concrete Powder", Material.CONCRETE_POWDER, 3));
        registeredBlocks.add(new BaseItem("Yellow Concrete Powder", Material.CONCRETE_POWDER, 4));
        registeredBlocks.add(new BaseItem("Lime Concrete Powder", Material.CONCRETE_POWDER, 5));
        registeredBlocks.add(new BaseItem("Pink Concrete Powder", Material.CONCRETE_POWDER, 6));
        registeredBlocks.add(new BaseItem("Gray Concrete Powder", Material.CONCRETE_POWDER, 7));
        registeredBlocks.add(new BaseItem("Light Gray Concrete Powder", Material.CONCRETE_POWDER, 8));
        registeredBlocks.add(new BaseItem("Cyan Concrete Powder", Material.CONCRETE_POWDER, 9));
        registeredBlocks.add(new BaseItem("Purple Concrete Powder", Material.CONCRETE_POWDER, 10));
        registeredBlocks.add(new BaseItem("Blue Concrete Powder", Material.CONCRETE_POWDER, 11));
        registeredBlocks.add(new BaseItem("Brown Concrete Powder", Material.CONCRETE_POWDER, 12));
        registeredBlocks.add(new BaseItem("Green Concrete Powder", Material.CONCRETE_POWDER, 13));
        registeredBlocks.add(new BaseItem("Red Concrete Powder", Material.CONCRETE_POWDER, 14));
        registeredBlocks.add(new BaseItem("Black Concrete Powder", Material.CONCRETE_POWDER, 15));
        registeredBlocks.add(new BaseItem("Structure Block", Material.STRUCTURE_BLOCK));

        registeredBlocks.add(new BaseItem("Iron Shovel", Material.IRON_SPADE));
        registeredBlocks.add(new BaseItem("Iron Pickaxe", Material.IRON_PICKAXE));
        registeredBlocks.add(new BaseItem("Iron Axe", Material.IRON_AXE));
        registeredBlocks.add(new BaseItem("Flint and Steel", Material.FLINT_AND_STEEL));
        registeredBlocks.add(new BaseItem("Apple", Material.APPLE));
        registeredBlocks.add(new BaseItem("Bow", Material.BOW));
        registeredBlocks.add(new BaseItem("ARROW", Material.ARROW));
        registeredBlocks.add(new BaseItem("Coal", Material.COAL));
        registeredBlocks.add(new BaseItem("Charcoal", Material.COAL, 1));
        registeredBlocks.add(new BaseItem("Diamond", Material.DIAMOND));
        registeredBlocks.add(new BaseItem("Iron Ingot", Material.IRON_INGOT));
        registeredBlocks.add(new BaseItem("Gold Ingot", Material.GOLD_INGOT));
        registeredBlocks.add(new BaseItem("Iron Sword", Material.IRON_SWORD));
        registeredBlocks.add(new BaseItem("Wood Sword", Material.WOOD_SWORD));
        registeredBlocks.add(new BaseItem("Wood Axe", Material.WOOD_AXE));
        registeredBlocks.add(new BaseItem("Stone Sword", Material.STONE_SWORD));
        registeredBlocks.add(new BaseItem("Stone Shovel", Material.STONE_SPADE));
        registeredBlocks.add(new BaseItem("Stone Pickaxe", Material.STONE_PICKAXE));
        registeredBlocks.add(new BaseItem("Stone Axe", Material.STONE_AXE));
        registeredBlocks.add(new BaseItem("Diamond Sword", Material.DIAMOND_SWORD));
        registeredBlocks.add(new BaseItem("Diamond Shovel", Material.DIAMOND_SPADE));
        registeredBlocks.add(new BaseItem("Diamond Pickaxe", Material.DIAMOND_PICKAXE));
        registeredBlocks.add(new BaseItem("Diamond Axe", Material.DIAMOND_AXE));
        registeredBlocks.add(new BaseItem("Stick", Material.STICK));
        registeredBlocks.add(new BaseItem("Bowl", Material.BOWL));
        registeredBlocks.add(new BaseItem("Mushroom Stew", Material.MUSHROOM_SOUP));
        registeredBlocks.add(new BaseItem("Gold Sword", Material.GOLD_SWORD));
        registeredBlocks.add(new BaseItem("Gold Shovel", Material.GOLD_SPADE));
        registeredBlocks.add(new BaseItem("Gold Axe", Material.GOLD_AXE));
        registeredBlocks.add(new BaseItem("String", Material.STRING));
        registeredBlocks.add(new BaseItem("Feather", Material.FEATHER));
        registeredBlocks.add(new BaseItem("Gunpowder", Material.SULPHUR));
        registeredBlocks.add(new BaseItem("Wooden Hoe", Material.WOOD_HOE));
        registeredBlocks.add(new BaseItem("Stone Hoe", Material.STONE_HOE));
        registeredBlocks.add(new BaseItem("Iron Hoe", Material.IRON_HOE));
        registeredBlocks.add(new BaseItem("Diamond Hoe", Material.DIAMOND_HOE));
        registeredBlocks.add(new BaseItem("Gold Hoe", Material.GOLD_HOE));
        registeredBlocks.add(new BaseItem("Wheat Seeds", Material.SEEDS));
        registeredBlocks.add(new BaseItem("Wheat", Material.WHEAT));
        registeredBlocks.add(new BaseItem("Bread", Material.BREAD));
        registeredBlocks.add(new BaseItem("Leather Cap", Material.LEATHER_HELMET));
        registeredBlocks.add(new BaseItem("Leather Tunic", Material.LEATHER_CHESTPLATE));
        registeredBlocks.add(new BaseItem("Leather Pants", Material.LEATHER_LEGGINGS));
        registeredBlocks.add(new BaseItem("Leather Boots", Material.LEATHER_BOOTS));
        registeredBlocks.add(new BaseItem("Chainmail Cap", Material.CHAINMAIL_HELMET));
        registeredBlocks.add(new BaseItem("Chainmail Tunic", Material.CHAINMAIL_CHESTPLATE));
        registeredBlocks.add(new BaseItem("Chainmail Pants", Material.CHAINMAIL_LEGGINGS));
        registeredBlocks.add(new BaseItem("Chainmail Boots", Material.CHAINMAIL_BOOTS));
        registeredBlocks.add(new BaseItem("Iron Cap", Material.IRON_HELMET));
        registeredBlocks.add(new BaseItem("Iron Tunic", Material.IRON_CHESTPLATE));
        registeredBlocks.add(new BaseItem("Iron Pants", Material.IRON_LEGGINGS));
        registeredBlocks.add(new BaseItem("Iron Boots", Material.IRON_BOOTS));
        registeredBlocks.add(new BaseItem("Diamond Cap", Material.DIAMOND_HELMET));
        registeredBlocks.add(new BaseItem("Diamond Tunic", Material.DIAMOND_CHESTPLATE));
        registeredBlocks.add(new BaseItem("Diamond Pants", Material.DIAMOND_LEGGINGS));
        registeredBlocks.add(new BaseItem("Diamond boots", Material.DIAMOND_BOOTS));
        registeredBlocks.add(new BaseItem("Flint", Material.FLINT));
        registeredBlocks.add(new BaseItem("Raw Pork", Material.PORK));
        registeredBlocks.add(new BaseItem("Grilled Pork", Material.GRILLED_PORK));
        registeredBlocks.add(new BaseItem("Painting", Material.PAINTING));
        registeredBlocks.add(new BaseItem("Golden Apple", Material.GOLDEN_APPLE));
        registeredBlocks.add(new BaseItem("Enchanted Golden Apple", Material.GOLDEN_APPLE, 1));
        registeredBlocks.add(new BaseItem("Bucket", Material.BUCKET));
        registeredBlocks.add(new BaseItem("Water Bucket", Material.WATER_BUCKET));
        registeredBlocks.add(new BaseItem("Lava Bucket", Material.LAVA_BUCKET));
        registeredBlocks.add(new BaseItem("Minecart", Material.MINECART));
        registeredBlocks.add(new BaseItem("Saddle", Material.SADDLE));
        registeredBlocks.add(new BaseItem("Iron Door", Material.IRON_DOOR));
        registeredBlocks.add(new BaseItem("Redstone", Material.REDSTONE));
        registeredBlocks.add(new BaseItem("Snowball", Material.SNOW_BALL));
        registeredBlocks.add(new BaseItem("Oak Boat", Material.BOAT));
        registeredBlocks.add(new BaseItem("Leather", Material.LEATHER));
        registeredBlocks.add(new BaseItem("Milk Bucket", Material.MILK_BUCKET));
        registeredBlocks.add(new BaseItem("Brick", Material.BRICK));
        registeredBlocks.add(new BaseItem("Clay Ball", Material.CLAY_BALL));
        registeredBlocks.add(new BaseItem("Sugar Canes", Material.SUGAR_CANE));
        registeredBlocks.add(new BaseItem("Paper", Material.PAPER));
        registeredBlocks.add(new BaseItem("Book", Material.BOOK));
        registeredBlocks.add(new BaseItem("Slimeball", Material.SLIME_BALL));
        registeredBlocks.add(new BaseItem("Chest Minecart", Material.STORAGE_MINECART));
        registeredBlocks.add(new BaseItem("Furnace Minecart", Material.POWERED_MINECART));
        registeredBlocks.add(new BaseItem("Egg", Material.EGG));
        registeredBlocks.add(new BaseItem("Compass", Material.COMPASS));
        registeredBlocks.add(new BaseItem("Fishing Rod", Material.FISHING_ROD));
        registeredBlocks.add(new BaseItem("Clock", Material.WATCH));
        registeredBlocks.add(new BaseItem("Glowstone Dust", Material.GLOWSTONE_DUST));
        registeredBlocks.add(new BaseItem("Raw Fish", Material.RAW_FISH));
        registeredBlocks.add(new BaseItem("Raw Salmon", Material.RAW_FISH, 1));
        registeredBlocks.add(new BaseItem("ClownFish", Material.RAW_FISH, 2));
        registeredBlocks.add(new BaseItem("PufferFish", Material.RAW_FISH, 3));
        registeredBlocks.add(new BaseItem("Cooked Fish", Material.COOKED_FISH));
        registeredBlocks.add(new BaseItem("Cooked Salmon", Material.COOKED_FISH, 1));
        registeredBlocks.add(new BaseItem("Ink Sac", Material.INK_SACK));
        registeredBlocks.add(new BaseItem("Rose Red", Material.INK_SACK, 1));
        registeredBlocks.add(new BaseItem("Cactus Green", Material.INK_SACK, 2));
        registeredBlocks.add(new BaseItem("Coco Beans", Material.INK_SACK, 3));
        registeredBlocks.add(new BaseItem("Lapis Lazuli", Material.INK_SACK, 4));
        registeredBlocks.add(new BaseItem("Purple Dye", Material.INK_SACK, 5));
        registeredBlocks.add(new BaseItem("Cyan Dye", Material.INK_SACK, 6));
        registeredBlocks.add(new BaseItem("Light Gray Dye", Material.INK_SACK, 7));
        registeredBlocks.add(new BaseItem("Gray Dye", Material.INK_SACK, 8));
        registeredBlocks.add(new BaseItem("Pink Dye", Material.INK_SACK, 9));
        registeredBlocks.add(new BaseItem("Lime Dye", Material.INK_SACK, 10));
        registeredBlocks.add(new BaseItem("Dandelion Yellow", Material.INK_SACK, 11));
        registeredBlocks.add(new BaseItem("Light Blue Dye", Material.INK_SACK, 12));
        registeredBlocks.add(new BaseItem("Magenta Dye", Material.INK_SACK, 13));
        registeredBlocks.add(new BaseItem("Orange Dye", Material.INK_SACK, 14));
        registeredBlocks.add(new BaseItem("Bone Meal", Material.INK_SACK, 15));
        registeredBlocks.add(new BaseItem("Bone", Material.BONE));
        registeredBlocks.add(new BaseItem("Sugar", Material.SUGAR));
        registeredBlocks.add(new BaseItem("Cake", Material.CAKE));
        registeredBlocks.add(new BaseItem("Bed", Material.BED));
        registeredBlocks.add(new BaseItem("Redstone Repeater", Material.DIODE_BLOCK_OFF));
        registeredBlocks.add(new BaseItem("Cookie", Material.COOKIE));
        registeredBlocks.add(new BaseItem("Map", Material.MAP));
        registeredBlocks.add(new BaseItem("Shears", Material.SHEARS));
        registeredBlocks.add(new BaseItem("Melon", Material.MELON));
        registeredBlocks.add(new BaseItem("Pumpkin Seeds", Material.PUMPKIN_SEEDS));
        registeredBlocks.add(new BaseItem("Melon Seeds", Material.MELON_SEEDS));
        registeredBlocks.add(new BaseItem("Raw Beef", Material.RAW_BEEF));
        registeredBlocks.add(new BaseItem("Steak", Material.COOKED_BEEF));
        registeredBlocks.add(new BaseItem("Raw Chicken", Material.RAW_CHICKEN));
        registeredBlocks.add(new BaseItem("Cooked Chicken", Material.COOKED_CHICKEN));
        registeredBlocks.add(new BaseItem("Rotten Flesh", Material.ROTTEN_FLESH));
        registeredBlocks.add(new BaseItem("Ender Pearl", Material.ENDER_PEARL));
        registeredBlocks.add(new BaseItem("Blaze Rod", Material.BLAZE_ROD));
        registeredBlocks.add(new BaseItem("Ghast Tear", Material.GHAST_TEAR));
        registeredBlocks.add(new BaseItem("Gold Nugget", Material.GOLD_NUGGET));
        registeredBlocks.add(new BaseItem("Potion", Material.POTION));
        registeredBlocks.add(new BaseItem("Glass Bottle", Material.GLASS_BOTTLE));
        registeredBlocks.add(new BaseItem("Spider Eye", Material.SPIDER_EYE));
        registeredBlocks.add(new BaseItem("Fermented Spider Eye", Material.FERMENTED_SPIDER_EYE));
        registeredBlocks.add(new BaseItem("Blaze Powder", Material.BLAZE_POWDER));
        registeredBlocks.add(new BaseItem("Magma Cream", Material.MAGMA_CREAM));
        registeredBlocks.add(new BaseItem("Brewing Stand", Material.BREWING_STAND));
        registeredBlocks.add(new BaseItem("Eye of Ender", Material.EYE_OF_ENDER));
        registeredBlocks.add(new BaseItem("Glistening Melon", Material.SPECKLED_MELON));
        registeredBlocks.add(new BaseItem("Spawn Egg", Material.MONSTER_EGG));
        registeredBlocks.add(new BaseItem("Spawn Elder Guardian", Material.MONSTER_EGG, 4));
        registeredBlocks.add(new BaseItem("Spawn Wither", Material.MONSTER_EGG, 5));
        registeredBlocks.add(new BaseItem("Spawn Stray", Material.MONSTER_EGG, 6));
        registeredBlocks.add(new BaseItem("Spawn Husk", Material.MONSTER_EGG, 23));
        registeredBlocks.add(new BaseItem("Spawn Zombie Villager", Material.MONSTER_EGG, 27));
        registeredBlocks.add(new BaseItem("Spawn Skeleton Horse", Material.MONSTER_EGG, 28));
        registeredBlocks.add(new BaseItem("Spawn Zombie Horse", Material.MONSTER_EGG, 29));
        registeredBlocks.add(new BaseItem("Spawn Donkey", Material.MONSTER_EGG, 31));
        registeredBlocks.add(new BaseItem("Spawn Mule", Material.MONSTER_EGG, 32));
        registeredBlocks.add(new BaseItem("Spawn Evoker", Material.MONSTER_EGG, 34));
        registeredBlocks.add(new BaseItem("Spawn Vex", Material.MONSTER_EGG, 35));
        registeredBlocks.add(new BaseItem("Spawn Vindicator", Material.MONSTER_EGG, 36));
        registeredBlocks.add(new BaseItem("Spawn Creeper", Material.MONSTER_EGG, 50));
        registeredBlocks.add(new BaseItem("Spawn Skeleton", Material.MONSTER_EGG, 51));
        registeredBlocks.add(new BaseItem("Spawn Spider", Material.MONSTER_EGG, 52));
        registeredBlocks.add(new BaseItem("Spawn Zombie", Material.MONSTER_EGG, 54));
        registeredBlocks.add(new BaseItem("Spawn Slime", Material.MONSTER_EGG, 55));
        registeredBlocks.add(new BaseItem("Spawn Ghast", Material.MONSTER_EGG, 56));
        registeredBlocks.add(new BaseItem("Spawn Zombie Pigman", Material.MONSTER_EGG, 57));
        registeredBlocks.add(new BaseItem("Spawn Enderman", Material.MONSTER_EGG, 58));
        registeredBlocks.add(new BaseItem("Spawn Cave Spider", Material.MONSTER_EGG, 59));
        registeredBlocks.add(new BaseItem("Spawn Silverfish", Material.MONSTER_EGG, 60));
        registeredBlocks.add(new BaseItem("Spawn Blaze", Material.MONSTER_EGG, 61));
        registeredBlocks.add(new BaseItem("Spawn Magma Cube", Material.MONSTER_EGG, 62));
        registeredBlocks.add(new BaseItem("Spawn Bat", Material.MONSTER_EGG, 65));
        registeredBlocks.add(new BaseItem("Spawn Witch", Material.MONSTER_EGG, 66));
        registeredBlocks.add(new BaseItem("Spawn Endermite", Material.MONSTER_EGG, 67));
        registeredBlocks.add(new BaseItem("Spawn Guardian", Material.MONSTER_EGG, 68));
        registeredBlocks.add(new BaseItem("Spawn Shulker", Material.MONSTER_EGG, 69));
        registeredBlocks.add(new BaseItem("Spawn Pig", Material.MONSTER_EGG, 90));
        registeredBlocks.add(new BaseItem("Spawn Sheep", Material.MONSTER_EGG, 91));
        registeredBlocks.add(new BaseItem("Spawn Cow", Material.MONSTER_EGG, 92));
        registeredBlocks.add(new BaseItem("Spawn Chicken", Material.MONSTER_EGG, 93));
        registeredBlocks.add(new BaseItem("Spawn Squid", Material.MONSTER_EGG, 94));
        registeredBlocks.add(new BaseItem("Spawn Wolf", Material.MONSTER_EGG, 95));
        registeredBlocks.add(new BaseItem("Spawn Mooshroom", Material.MONSTER_EGG, 96));
        registeredBlocks.add(new BaseItem("Spawn Ocelot", Material.MONSTER_EGG, 98));
        registeredBlocks.add(new BaseItem("Spawn Horse", Material.MONSTER_EGG, 100));
        registeredBlocks.add(new BaseItem("Spawn Rabbit", Material.MONSTER_EGG, 101));
        registeredBlocks.add(new BaseItem("Spawn Polar Bear", Material.MONSTER_EGG, 102));
        registeredBlocks.add(new BaseItem("Spawn Llama", Material.MONSTER_EGG, 103));
        registeredBlocks.add(new BaseItem("Spawn Villager", Material.MONSTER_EGG, 120));
        registeredBlocks.add(new BaseItem("Bottle-O-Enchanting", Material.EXP_BOTTLE));
        registeredBlocks.add(new BaseItem("Fire Charge", Material.FIREWORK_CHARGE));
        registeredBlocks.add(new BaseItem("Book and Quill", Material.BOOK_AND_QUILL));
        registeredBlocks.add(new BaseItem("Written Book", Material.WRITTEN_BOOK));
        registeredBlocks.add(new BaseItem("Emerald", Material.EMERALD));
        registeredBlocks.add(new BaseItem("Item Frame", Material.ITEM_FRAME));
        registeredBlocks.add(new BaseItem("Carrot", Material.CARROT));
        registeredBlocks.add(new BaseItem("Potato", Material.POTATO));
        registeredBlocks.add(new BaseItem("Baked Potato", Material.BAKED_POTATO));
        registeredBlocks.add(new BaseItem("Poisonous Potato", Material.POISONOUS_POTATO));
        registeredBlocks.add(new BaseItem("Empty Map", Material.EMPTY_MAP));
        registeredBlocks.add(new BaseItem("Golden Carrot", Material.GOLDEN_CARROT));
        registeredBlocks.add(new BaseItem("Wither Skull", Material.SKULL, 1));
        registeredBlocks.add(new BaseItem("Zombie Skull", Material.SKULL, 2));
        registeredBlocks.add(new BaseItem("Player Skull", Material.SKULL, 3));
        registeredBlocks.add(new BaseItem("Creeper Skull", Material.SKULL, 4));
        registeredBlocks.add(new BaseItem("Dragon Skull", Material.SKULL, 5));
        registeredBlocks.add(new BaseItem("Carrot on a Stick", Material.CARROT_STICK));
        registeredBlocks.add(new BaseItem("Nether Star", Material.NETHER_STAR));
        registeredBlocks.add(new BaseItem("Pumpkin Pie", Material.PUMPKIN_PIE));
        registeredBlocks.add(new BaseItem("Firework Rocket", Material.FIREWORK));
        registeredBlocks.add(new BaseItem("Firework Star", Material.FIREWORK_CHARGE));
        registeredBlocks.add(new BaseItem("Enchanted Book", Material.ENCHANTED_BOOK));
        registeredBlocks.add(new BaseItem("Nether Brick", Material.NETHER_BRICK));
        registeredBlocks.add(new BaseItem("Raw Rabbit", Material.RABBIT));
        registeredBlocks.add(new BaseItem("Cooked Rabbit", Material.COOKED_RABBIT));
        registeredBlocks.add(new BaseItem("Rabbit Foot", Material.RABBIT_FOOT));
        registeredBlocks.add(new BaseItem("Rabbit Hide", Material.RABBIT_HIDE));
        registeredBlocks.add(new BaseItem("Armor Stand", Material.ARMOR_STAND));
        registeredBlocks.add(new BaseItem("Iron Horse Armor", Material.IRON_BARDING));
        registeredBlocks.add(new BaseItem("Gold Horse Armor", Material.GOLD_BARDING));
        registeredBlocks.add(new BaseItem("Diamond Horse Armor", Material.DIAMOND_BARDING));
        registeredBlocks.add(new BaseItem("Lead", Material.LEASH));
        registeredBlocks.add(new BaseItem("Name Tag", Material.NAME_TAG));
        registeredBlocks.add(new BaseItem("Minecart with Command Block", Material.COMMAND_MINECART));
        registeredBlocks.add(new BaseItem("Raw Mutton", Material.MUTTON));
        registeredBlocks.add(new BaseItem("Cooked Mutton", Material.COOKED_MUTTON));
        registeredBlocks.add(new BaseItem("Banner", Material.BANNER));
        registeredBlocks.add(new BaseItem("Beetroot", Material.BEETROOT));
        registeredBlocks.add(new BaseItem("Beetroot Seeds", Material.BEETROOT_SEEDS));
        registeredBlocks.add(new BaseItem("Beetroot Soup", Material.BEETROOT_SOUP));
        registeredBlocks.add(new BaseItem("Dragon Breath", Material.DRAGONS_BREATH));
        registeredBlocks.add(new BaseItem("Splash Potion", Material.SPLASH_POTION));
        registeredBlocks.add(new BaseItem("Spectral Arrow", Material.SPECTRAL_ARROW));
        registeredBlocks.add(new BaseItem("Tipped Arrow", Material.TIPPED_ARROW));
        registeredBlocks.add(new BaseItem("Lingering Potion", Material.LINGERING_POTION));
        registeredBlocks.add(new BaseItem("Shield", Material.SHIELD));
        registeredBlocks.add(new BaseItem("Elytra", Material.ELYTRA));
        registeredBlocks.add(new BaseItem("Spruce Boat", Material.BOAT_SPRUCE));
        registeredBlocks.add(new BaseItem("Birch Boat", Material.BOAT_BIRCH));
        registeredBlocks.add(new BaseItem("Jungle Boat", Material.BOAT_JUNGLE));
        registeredBlocks.add(new BaseItem("Acacia Boat", Material.BOAT_ACACIA));
        registeredBlocks.add(new BaseItem("Dark Oak Boat", Material.BOAT_DARK_OAK));
        registeredBlocks.add(new BaseItem("Totem of Undying", Material.TOTEM));
        registeredBlocks.add(new BaseItem("Shulker Shell", Material.SHULKER_SHELL));
        registeredBlocks.add(new BaseItem("Iron Nugget", Material.IRON_NUGGET));
        registeredBlocks.add(new BaseItem("Disc 13", Material.GOLD_RECORD));
        registeredBlocks.add(new BaseItem("Disc Cat", Material.GREEN_RECORD));
        registeredBlocks.add(new BaseItem("Disc Blocks", Material.RECORD_3));
        registeredBlocks.add(new BaseItem("Disc Chirp", Material.RECORD_4));
        registeredBlocks.add(new BaseItem("Disc Far", Material.RECORD_5));
        registeredBlocks.add(new BaseItem("Disc Mall", Material.RECORD_6));
        registeredBlocks.add(new BaseItem("Disc Mellohi", Material.RECORD_7));
        registeredBlocks.add(new BaseItem("Disc Stal", Material.RECORD_8));
        registeredBlocks.add(new BaseItem("Disc Strad", Material.RECORD_9));
        registeredBlocks.add(new BaseItem("Disc Ward", Material.RECORD_10));
        registeredBlocks.add(new BaseItem("Disc 11", Material.RECORD_11));
        registeredBlocks.add(new BaseItem("Disc Wait", Material.RECORD_12));
    }

    public static Optional<BaseItem> find(String name) {
        List<BaseItem> items = registeredBlocks.stream().filter(item -> item.getName().equalsIgnoreCase(name)).collect(Collectors.toList());
        if (items.size() > 1) {
            System.out.println("Somehow got multiple items from search result? " + name);
            return Optional.empty();
        }
        return items.size() == 1 ? Optional.of(items.get(0)) : Optional.empty();
    }
}