package me.ifydev.core.spigot.items;

import lombok.Getter;
import org.bukkit.Material;
import org.bukkit.potion.PotionData;
import org.bukkit.potion.PotionType;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * @author Innectic
 * @since 10/5/2017
 */
public class BlockRegistry {
    @Getter private static List<BaseItem> registered = new ArrayList<>();

    @Getter private static boolean setup = false;

    public static void setup() {
        if (setup) return;
        setup = true;

        registered.add(new BaseItem("Stone", Material.STONE));
        registered.add(new BaseItem("Granite", Material.GRANITE));
        registered.add(new BaseItem("Polished Granite", Material.POLISHED_GRANITE));
        registered.add(new BaseItem("Diorite", Material.DIORITE));
        registered.add(new BaseItem("Polished Diorite", Material.POLISHED_DIORITE));
        registered.add(new BaseItem("Andesite", Material.ANDESITE));
        registered.add(new BaseItem("Polished Andesite", Material.POLISHED_ANDESITE));
        registered.add(new BaseItem("Grass", Material.GRASS));
        registered.add(new BaseItem("Dirt", Material.DIRT));
        registered.add(new BaseItem("Coarse Dirt", Material.COARSE_DIRT));
        registered.add(new BaseItem("Podzol", Material.PODZOL));
        registered.add(new BaseItem("Cobblestone", Material.COBBLESTONE));
        registered.add(new BaseItem("Oak Plank", Material.OAK_PLANKS));
        registered.add(new BaseItem("Spruce Plank", Material.SPRUCE_PLANKS));
        registered.add(new BaseItem("Birch Plank", Material.BIRCH_PLANKS));
        registered.add(new BaseItem("Jungle Plank", Material.JUNGLE_PLANKS));
        registered.add(new BaseItem("Acacia Plank", Material.ACACIA_PLANKS));
        registered.add(new BaseItem("Dark Oak Plank", Material.DARK_OAK_PLANKS));
        registered.add(new BaseItem("Oak Sapling", Material.OAK_SAPLING));
        registered.add(new BaseItem("Spruce Sapling", Material.SPRUCE_SAPLING));
        registered.add(new BaseItem("Birch Sapling", Material.BIRCH_SAPLING));
        registered.add(new BaseItem("Jungle Sapling", Material.JUNGLE_SAPLING));
        registered.add(new BaseItem("Acacia Sapling", Material.ACACIA_SAPLING));
        registered.add(new BaseItem("Bedrock", Material.BEDROCK));
        registered.add(new BaseItem("Sand", Material.SAND));
        registered.add(new BaseItem("Red Sand", Material.RED_SAND));
        registered.add(new BaseItem("Gravel", Material.GRAVEL));
        registered.add(new BaseItem("Gold Ore", Material.GOLD_ORE));
        registered.add(new BaseItem("Iron Ore", Material.IRON_ORE));
        registered.add(new BaseItem("Coal Ore", Material.COAL_ORE));
        registered.add(new BaseItem("Lapis Lazuli Ore", Material.LAPIS_ORE));
        registered.add(new BaseItem("Sponge", Material.SPONGE));
        registered.add(new BaseItem("Wet Sponge", Material.WET_SPONGE));
        registered.add(new BaseItem("Glass", Material.GLASS));
        registered.add(new BaseItem("Lapis Lazuli Block", Material.LAPIS_BLOCK));
        registered.add(new BaseItem("Dispenser", Material.DISPENSER));
        registered.add(new BaseItem("Sandstone", Material.SANDSTONE));
        registered.add(new BaseItem("Chiseled Sandstone", Material.CHISELED_SANDSTONE));
        registered.add(new BaseItem("Smooth Sandstone", Material.SMOOTH_SANDSTONE));
        registered.add(new BaseItem("Note Block", Material.NOTE_BLOCK));
        registered.add(new BaseItem("Bed", Material.WHITE_BED));
        registered.add(new BaseItem("White Bed", Material.WHITE_BED));
        registered.add(new BaseItem("Black Bed", Material.BLACK_BED));
        registered.add(new BaseItem("Green Bed", Material.GREEN_BED));
        registered.add(new BaseItem("Dark Aqua Bed", Material.BLUE_BED));
        registered.add(new BaseItem("Blue Bed", Material.BLUE_BED));
        registered.add(new BaseItem("Dark Red Bed", Material.RED_BED));
        registered.add(new BaseItem("Purple Bed", Material.PURPLE_BED));
        registered.add(new BaseItem("Gold Bed", Material.YELLOW_BED));
        registered.add(new BaseItem("Gray Bed", Material.LIGHT_GRAY_BED));
        registered.add(new BaseItem("Dark Gray Bed", Material.GRAY_BED));
        registered.add(new BaseItem("Indigo Bed", Material.BLUE_BED));
        registered.add(new BaseItem("Lime Bed", Material.LIME_BED));
        registered.add(new BaseItem("Aqua Bed", Material.LIGHT_BLUE_BED));
        registered.add(new BaseItem("Light Blue Bed", Material.LIGHT_BLUE_BED));
        registered.add(new BaseItem("Red Bed", Material.RED_BED));
        registered.add(new BaseItem("Pink Bed", Material.PINK_BED));
        registered.add(new BaseItem("Yellow Bed", Material.YELLOW_BED));
        registered.add(new BaseItem("Brown Bed", Material.BROWN_BED));
        registered.add(new BaseItem("Powered Rail", Material.POWERED_RAIL));
        registered.add(new BaseItem("Detector Rail", Material.DETECTOR_RAIL));
        registered.add(new BaseItem("Piston", Material.PISTON));
        registered.add(new BaseItem("Sticky Piston", Material.STICKY_PISTON));
        registered.add(new BaseItem("Cobweb", Material.COBWEB));

        registered.add(new BaseItem("Dead Bush", Material.DEAD_BUSH));
        registered.add(new BaseItem("Dead Shrub", Material.DEAD_BUSH));

        registered.add(new BaseItem("Tall Grass", Material.GRASS));
        registered.add(new BaseItem("Fern", Material.FERN));
        registered.add(new BaseItem("White Wool", Material.WHITE_WOOL));
        registered.add(new BaseItem("Orange Wool", Material.ORANGE_WOOL));
        registered.add(new BaseItem("Magenta Wool", Material.MAGENTA_WOOL));
        registered.add(new BaseItem("Light Blue Wool", Material.LIGHT_BLUE_WOOL));
        registered.add(new BaseItem("Yellow Wool", Material.YELLOW_WOOL));
        registered.add(new BaseItem("Lime Wool", Material.LIME_WOOL));
        registered.add(new BaseItem("Pink Wool", Material.PINK_WOOL));
        registered.add(new BaseItem("Gray Wool", Material.GRAY_WOOL));
        registered.add(new BaseItem("Light Gray Wool", Material.LIGHT_GRAY_WOOL));
        registered.add(new BaseItem("Cyan Wool", Material.CYAN_WOOL));
        registered.add(new BaseItem("Purple Wool", Material.PURPLE_WOOL));
        registered.add(new BaseItem("Blue Wool", Material.BLUE_WOOL));
        registered.add(new BaseItem("Brown Wool", Material.BROWN_WOOL));
        registered.add(new BaseItem("Green Wool", Material.GREEN_WOOL));
        registered.add(new BaseItem("Red Wool", Material.RED_WOOL));
        registered.add(new BaseItem("Black Wool", Material.BLACK_WOOL));
        registered.add(new BaseItem("Dandelion", Material.DANDELION));
        registered.add(new BaseItem("Poppy", Material.POPPY));
        registered.add(new BaseItem("Blue Orchid", Material.BLUE_ORCHID));
        registered.add(new BaseItem("Allium", Material.ALLIUM));
        registered.add(new BaseItem("Azure Bluet", Material.AZURE_BLUET));
        registered.add(new BaseItem("Red Tulip", Material.RED_TULIP));
        registered.add(new BaseItem("Orange Tulip", Material.ORANGE_TULIP));
        registered.add(new BaseItem("White Tulip", Material.WHITE_TULIP));
        registered.add(new BaseItem("Pink Tulip", Material.PINK_TULIP));
        registered.add(new BaseItem("Oxeye Daisy", Material.OXEYE_DAISY));
        registered.add(new BaseItem("Brown Mushroom", Material.BROWN_MUSHROOM));
        registered.add(new BaseItem("Red Mushroom", Material.RED_MUSHROOM));
        registered.add(new BaseItem("Gold Block", Material.GOLD_BLOCK));
        registered.add(new BaseItem("Iron Block", Material.IRON_BLOCK));
        registered.add(new BaseItem("Stone Slab", Material.STONE_SLAB));
        registered.add(new BaseItem("Sandstone Slab", Material.SANDSTONE_SLAB));
        registered.add(new BaseItem("Oak Slab", Material.OAK_SLAB));
        registered.add(new BaseItem("Acacia Slab", Material.ACACIA_SLAB));
        registered.add(new BaseItem("Birch Slab", Material.BIRCH_SLAB));
        registered.add(new BaseItem("Brick Slab", Material.BRICK_SLAB));
        registered.add(new BaseItem("Cobblestone Slab", Material.COBBLESTONE_SLAB));
        registered.add(new BaseItem("Dark Oak Slab", Material.DARK_OAK_SLAB));
        registered.add(new BaseItem("Dark Prismarine Slab", Material.DARK_PRISMARINE_SLAB));
        registered.add(new BaseItem("Prismarine Shard", Material.PRISMARINE_SHARD));
        registered.add(new BaseItem("Prismarine Crystal", Material.PRISMARINE_CRYSTALS));
        registered.add(new BaseItem("Jungle Slab", Material.JUNGLE_SLAB));
        registered.add(new BaseItem("Nether Brick Slab", Material.NETHER_BRICK_SLAB));
        registered.add(new BaseItem("Petrified Oak Slab", Material.PETRIFIED_OAK_SLAB));
        registered.add(new BaseItem("Prismarine Brick Slab", Material.PRISMARINE_BRICK_SLAB));
        registered.add(new BaseItem("Prismarine Slab", Material.PRISMARINE_SLAB));
        registered.add(new BaseItem("Purpur Slab", Material.PURPUR_SLAB));
        registered.add(new BaseItem("Quartz Slab", Material.QUARTZ_SLAB));
        registered.add(new BaseItem("Sandstone Slab", Material.SANDSTONE_SLAB));
        registered.add(new BaseItem("Spruce Slab", Material.SPRUCE_SLAB));
        registered.add(new BaseItem("Stone Brick Slab", Material.STONE_BRICK_SLAB));
        registered.add(new BaseItem("Stone Slab", Material.STONE_SLAB));
        registered.add(new BaseItem("Bricks", Material.BRICKS));
        registered.add(new BaseItem("TNT", Material.TNT));
        registered.add(new BaseItem("Bookshelf", Material.BOOKSHELF));
        registered.add(new BaseItem("Mossy Cobblestone", Material.MOSSY_COBBLESTONE));
        registered.add(new BaseItem("Obsidian", Material.OBSIDIAN));
        registered.add(new BaseItem("Torch", Material.TORCH));
        registered.add(new BaseItem("Stone Brick Stairs", Material.STONE_BRICK_STAIRS));
        registered.add(new BaseItem("Sandstone Stairs", Material.SANDSTONE_STAIRS));
        registered.add(new BaseItem("Oak Stairs", Material.OAK_STAIRS));
        registered.add(new BaseItem("Acacia Stairs", Material.ACACIA_STAIRS));
        registered.add(new BaseItem("Birch Stairs", Material.BIRCH_STAIRS));
        registered.add(new BaseItem("Brick Stairs", Material.BRICK_STAIRS));
        registered.add(new BaseItem("Cobblestone Stairs", Material.COBBLESTONE_STAIRS));
        registered.add(new BaseItem("Dark Oak Stairs", Material.DARK_OAK_STAIRS));
        registered.add(new BaseItem("Dark Prismarine Stairs", Material.DARK_PRISMARINE_STAIRS));
        registered.add(new BaseItem("Jungle Stairs", Material.JUNGLE_STAIRS));
        registered.add(new BaseItem("Nether Brick Stairs", Material.NETHER_BRICK_STAIRS));
        registered.add(new BaseItem("Prismarine Brick Stairs", Material.PRISMARINE_BRICK_STAIRS));
        registered.add(new BaseItem("Prismarine Stairs", Material.PRISMARINE_STAIRS));
        registered.add(new BaseItem("Purpur Stairs", Material.PURPUR_STAIRS));
        registered.add(new BaseItem("Quartz Stairs", Material.QUARTZ_STAIRS));
        registered.add(new BaseItem("Sandstone Stairs", Material.SANDSTONE_STAIRS));
        registered.add(new BaseItem("Spruce Stairs", Material.SPRUCE_STAIRS));
        registered.add(new BaseItem("Cobblestone Stairs", Material.COBBLESTONE_STAIRS));
        registered.add(new BaseItem("Stone Stairs", Material.COBBLESTONE_STAIRS));
        registered.add(new BaseItem("Mossy Stone Brick Stairs", Material.MOSSY_STONE_BRICK_STAIRS));
        registered.add(new BaseItem("Mossy Stone Brick Slab", Material.MOSSY_STONE_BRICK_SLAB));
        registered.add(new BaseItem("Mossy Stone Brick Wall", Material.MOSSY_STONE_BRICK_WALL));
        registered.add(new BaseItem("Mossy Cobblestone Stairs", Material.MOSSY_COBBLESTONE_STAIRS));
        registered.add(new BaseItem("Mossy Cobblestone Slab", Material.MOSSY_COBBLESTONE_SLAB));
        registered.add(new BaseItem("Mossy Cobblestone Wall", Material.MOSSY_COBBLESTONE_WALL));
        registered.add(new BaseItem("Red Sandstone Stairs", Material.RED_SANDSTONE_STAIRS));
        registered.add(new BaseItem("Red Sandstone Slab", Material.RED_SANDSTONE_SLAB));
        registered.add(new BaseItem("Red Sandstone Wall", Material.RED_SANDSTONE_WALL));
        registered.add(new BaseItem("Andesite Stairs", Material.ANDESITE_STAIRS));
        registered.add(new BaseItem("Andesite Slab", Material.ANDESITE_SLAB));
        registered.add(new BaseItem("Andesite Wall", Material.ANDESITE_WALL));
        registered.add(new BaseItem("Diorite Stairs", Material.DIORITE_STAIRS));
        registered.add(new BaseItem("Diorite Slab", Material.DIORITE_SLAB));
        registered.add(new BaseItem("Diorite Wall", Material.DIORITE_WALL));
        registered.add(new BaseItem("Granite Stairs", Material.GRANITE_STAIRS));
        registered.add(new BaseItem("Granite Slab", Material.GRANITE_SLAB));
        registered.add(new BaseItem("Granite Wall", Material.GRANITE_WALL));
        registered.add(new BaseItem("Red Nether Brick Stairs", Material.RED_NETHER_BRICK_STAIRS));
        registered.add(new BaseItem("Red Nether Brick Slab", Material.RED_NETHER_BRICK_SLAB));
        registered.add(new BaseItem("Red Nether Brick Wall", Material.RED_NETHER_BRICK_WALL));
        registered.add(new BaseItem("End Stone Brick Stairs", Material.END_STONE_BRICK_STAIRS));
        registered.add(new BaseItem("End Stone Brick Slab", Material.END_STONE_BRICK_SLAB));
        registered.add(new BaseItem("End Stone Brick Wall", Material.END_STONE_BRICK_WALL));
        registered.add(new BaseItem("Barrel", Material.BARREL));
        registered.add(new BaseItem("Bell", Material.BELL));
        registered.add(new BaseItem("Blast Furnace", Material.BLAST_FURNACE));
        registered.add(new BaseItem("Cartography Table", Material.CARTOGRAPHY_TABLE));
        registered.add(new BaseItem("Composter", Material.COMPOSTER));
        registered.add(new BaseItem("Grindstone", Material.GRINDSTONE));
        registered.add(new BaseItem("Lectern", Material.LECTERN));
        registered.add(new BaseItem("Loom", Material.LOOM));
        registered.add(new BaseItem("Smoker", Material.SMOKER));
        registered.add(new BaseItem("Stonecutter", Material.STONECUTTER));
        registered.add(new BaseItem("Fletching Table", Material.FLETCHING_TABLE));
        registered.add(new BaseItem("Smithing Table", Material.SMITHING_TABLE));
        registered.add(new BaseItem("Cornflower", Material.CORNFLOWER));
        registered.add(new BaseItem("Lily of the Valley", Material.LILY_OF_THE_VALLEY));
        registered.add(new BaseItem("Wither Rose", Material.WITHER_ROSE));
        registered.add(new BaseItem("Sweet Berry Bush", Material.SWEET_BERRY_BUSH));
        registered.add(new BaseItem("Sweet Berries", Material.SWEET_BERRIES));
        registered.add(new BaseItem("Crossbow", Material.CROSSBOW));
        registered.add(new BaseItem("Bamboo", Material.BAMBOO));
        registered.add(new BaseItem("Suspicious Stew", Material.SUSPICIOUS_STEW));
        registered.add(new BaseItem("Bamboo Sapling", Material.BAMBOO_SAPLING));

        registered.add(new BaseItem("Chest", Material.CHEST));
        registered.add(new BaseItem("Diamond Ore", Material.DIAMOND_ORE));
        registered.add(new BaseItem("Crafting Table", Material.CRAFTING_TABLE));
        registered.add(new BaseItem("Farmland", Material.FARMLAND));
        registered.add(new BaseItem("Furnace", Material.FURNACE));

        registered.add(new BaseItem("Acaica Sign", Material.ACACIA_SIGN));
        registered.add(new BaseItem("Birch Sign", Material.BIRCH_SIGN));
        registered.add(new BaseItem("Dark Oak Sign", Material.DARK_OAK_SIGN));
        registered.add(new BaseItem("Jungle Sign", Material.JUNGLE_SIGN));
        registered.add(new BaseItem("Oak Sign", Material.OAK_SIGN));
        registered.add(new BaseItem("Spruce Sign", Material.SPRUCE_SIGN));
        registered.add(new BaseItem("Sign", Material.OAK_SIGN));

        registered.add(new BaseItem("Oak Door", Material.OAK_DOOR));
        registered.add(new BaseItem("Birch Door", Material.BIRCH_DOOR));
        registered.add(new BaseItem("Dark Oak Door", Material.DARK_OAK_DOOR));
        registered.add(new BaseItem("Iron Door", Material.IRON_DOOR));
        registered.add(new BaseItem("Spruce Door", Material.SPRUCE_DOOR));
        registered.add(new BaseItem("Ladder", Material.LADDER));
        registered.add(new BaseItem("Rail", Material.RAIL));
        registered.add(new BaseItem("Activator Rail", Material.ACTIVATOR_RAIL));
        registered.add(new BaseItem("Detector Rail", Material.DETECTOR_RAIL));
        registered.add(new BaseItem("Powered Rail", Material.POWERED_RAIL));
        registered.add(new BaseItem("Cobblestone Stairs", Material.COBBLESTONE_STAIRS));
        registered.add(new BaseItem("Lever", Material.LEVER));
        registered.add(new BaseItem("Stone Pressure Plate", Material.STONE_PRESSURE_PLATE));
        registered.add(new BaseItem("Acacia Pressure Plate", Material.ACACIA_PRESSURE_PLATE));
        registered.add(new BaseItem("Oak Pressure Plate", Material.OAK_PRESSURE_PLATE));
        registered.add(new BaseItem("Birch Pressure Plate", Material.BIRCH_PRESSURE_PLATE));
        registered.add(new BaseItem("Dark Oak Pressure Plate", Material.DARK_OAK_PRESSURE_PLATE));
        registered.add(new BaseItem("Jungle Pressure Plate", Material.JUNGLE_PRESSURE_PLATE));
        registered.add(new BaseItem("Spruce Pressure Plate", Material.SPRUCE_PRESSURE_PLATE));
        registered.add(new BaseItem("Redstone Ore", Material.REDSTONE_ORE));
        registered.add(new BaseItem("Redstone Torch", Material.REDSTONE_TORCH));
        registered.add(new BaseItem("Stone Button", Material.STONE_BUTTON));
        registered.add(new BaseItem("Snow", Material.SNOW));
        registered.add(new BaseItem("Ice", Material.ICE));
        registered.add(new BaseItem("Scaffolding", Material.SCAFFOLDING));
        registered.add(new BaseItem("Lantern", Material.LANTERN));
        registered.add(new BaseItem("Jigsaw", Material.JIGSAW));
        registered.add(new BaseItem("Snow Block", Material.SNOW_BLOCK));
        registered.add(new BaseItem("Cactus", Material.CACTUS));
        registered.add(new BaseItem("Clay Block", Material.CLAY));
        registered.add(new BaseItem("Sugar Cane", Material.SUGAR_CANE));
        registered.add(new BaseItem("Jukebox", Material.JUKEBOX));
        registered.add(new BaseItem("Acacia Fence", Material.ACACIA_FENCE));
        registered.add(new BaseItem("Oak Fence", Material.OAK_FENCE));
        registered.add(new BaseItem("Birch Fence", Material.BIRCH_FENCE));
        registered.add(new BaseItem("Dark Oak Fence", Material.DARK_OAK_FENCE));
        registered.add(new BaseItem("Iron Fence", Material.IRON_BARS));
        registered.add(new BaseItem("Iron Bars", Material.IRON_BARS));
        registered.add(new BaseItem("Spruce Fence", Material.SPRUCE_FENCE));
        registered.add(new BaseItem("Pumpkin", Material.PUMPKIN));
        registered.add(new BaseItem("Netherrack", Material.NETHERRACK));
        registered.add(new BaseItem("Soul Sand", Material.SOUL_SAND));
        registered.add(new BaseItem("Glowstone", Material.GLOWSTONE));
        registered.add(new BaseItem("Jack-O-Lantern", Material.JACK_O_LANTERN));
        registered.add(new BaseItem("Cake", Material.CAKE));
        registered.add(new BaseItem("Redstone Repeater", Material.REPEATER));
        registered.add(new BaseItem("White Stained Glass", Material.WHITE_STAINED_GLASS));
        registered.add(new BaseItem("Orange Stained Glass", Material.ORANGE_STAINED_GLASS));
        registered.add(new BaseItem("Magenta Stained Glass", Material.MAGENTA_STAINED_GLASS));
        registered.add(new BaseItem("Light Blue Stained Glass", Material.LIGHT_BLUE_STAINED_GLASS));
        registered.add(new BaseItem("Yellow Stained Glass", Material.YELLOW_STAINED_GLASS));
        registered.add(new BaseItem("Lime Stained Glass", Material.LIME_STAINED_GLASS));
        registered.add(new BaseItem("Pink Stained Glass", Material.PINK_STAINED_GLASS));
        registered.add(new BaseItem("Gray Stained Glass", Material.GRAY_STAINED_GLASS));
        registered.add(new BaseItem("Light Gray Stained Glass", Material.LIGHT_GRAY_STAINED_GLASS));
        registered.add(new BaseItem("Cyan Stained Glass", Material.CYAN_STAINED_GLASS));
        registered.add(new BaseItem("Purple Stained Glass", Material.PURPLE_STAINED_GLASS));
        registered.add(new BaseItem("Blue Stained Glass", Material.BLUE_STAINED_GLASS));
        registered.add(new BaseItem("Brown Stained Glass", Material.BROWN_STAINED_GLASS));
        registered.add(new BaseItem("Green Stained Glass", Material.GREEN_STAINED_GLASS));
        registered.add(new BaseItem("Red Stained Glass", Material.RED_STAINED_GLASS));
        registered.add(new BaseItem("Black Stained Glass", Material.BLACK_STAINED_GLASS));

        registered.add(new BaseItem("Stone Monster Egg", Material.INFESTED_STONE));
        registered.add(new BaseItem("Cobblestone Monster Egg", Material.INFESTED_COBBLESTONE));
        registered.add(new BaseItem("Stone Brick Monster Egg", Material.INFESTED_STONE_BRICKS));
        registered.add(new BaseItem("Mossy Stone Brick Monster Egg", Material.INFESTED_MOSSY_STONE_BRICKS));
        registered.add(new BaseItem("Cracked Stone Brick Monster Egg", Material.INFESTED_CRACKED_STONE_BRICKS));

        registered.add(new BaseItem("Infested Stone", Material.INFESTED_STONE));
        registered.add(new BaseItem("Infested Cobblestone", Material.INFESTED_COBBLESTONE));
        registered.add(new BaseItem("Infested Stone Brick", Material.INFESTED_STONE_BRICKS));
        registered.add(new BaseItem("Infested Mossy Stone Brick", Material.INFESTED_MOSSY_STONE_BRICKS));
        registered.add(new BaseItem("Infested Cracked Stone Brick", Material.INFESTED_CRACKED_STONE_BRICKS));
        registered.add(new BaseItem("Infested Chiseled Stone Brick", Material.INFESTED_CHISELED_STONE_BRICKS));

        registered.add(new BaseItem("Stone Brick", Material.STONE_BRICKS));
        registered.add(new BaseItem("Mossy Stone Brick", Material.MOSSY_STONE_BRICKS));
        registered.add(new BaseItem("Cracked Stone Brick", Material.CRACKED_STONE_BRICKS));
        registered.add(new BaseItem("Chiseled Stone Brick", Material.CHISELED_STONE_BRICKS));
        registered.add(new BaseItem("Brown Mushroom Block", Material.BROWN_MUSHROOM_BLOCK));
        registered.add(new BaseItem("Red Mushroom Block", Material.RED_MUSHROOM_BLOCK));
        registered.add(new BaseItem("Glass Pane", Material.GLASS_PANE));
        registered.add(new BaseItem("White Stained Glass Pane", Material.WHITE_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Orange Stained Glass Pane", Material.ORANGE_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Magenta Stained Glass Pane", Material.MAGENTA_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Light Blue Stained Glass Pane", Material.LIGHT_BLUE_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Yellow Stained Glass Pane", Material.YELLOW_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Lime Stained Glass Pane", Material.LIME_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Pink Stained Glass Pane", Material.PINK_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Gray Stained Glass Pane", Material.GRAY_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Light Gray Stained Glass Pane", Material.LIGHT_GRAY_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Cyan Stained Glass Pane", Material.CYAN_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Purple Stained Glass Pane", Material.PURPLE_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Blue Stained Glass Pane", Material.BLUE_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Brown Stained Glass Pane", Material.BROWN_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Green Stained Glass Pane", Material.GREEN_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Black Stained Glass Pane", Material.BLACK_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Melon Block", Material.MELON));
        registered.add(new BaseItem("Vines", Material.VINE));
        registered.add(new BaseItem("Oak Fence Gate", Material.OAK_FENCE_GATE));
        registered.add(new BaseItem("Birch Fence Gate", Material.BIRCH_FENCE_GATE));
        registered.add(new BaseItem("Dark Oak Fence Gate", Material.DARK_OAK_FENCE_GATE));
        registered.add(new BaseItem("Jungle Fence Gate", Material.JUNGLE_FENCE_GATE));
        registered.add(new BaseItem("Spruce Fence Gate", Material.SPRUCE_FENCE_GATE));
        registered.add(new BaseItem("Brick Stairs", Material.BRICK_STAIRS));
        registered.add(new BaseItem("Mycelium", Material.MYCELIUM));
        registered.add(new BaseItem("Lily Pad", Material.LILY_PAD));
        registered.add(new BaseItem("Nether Brick", Material.NETHER_BRICK));
        registered.add(new BaseItem("Nether Brick Fence", Material.NETHER_BRICK_FENCE));
        registered.add(new BaseItem("Nether Brick Stairs", Material.NETHER_BRICK_STAIRS));
        registered.add(new BaseItem("Nether Wart", Material.NETHER_WART));
        registered.add(new BaseItem("Enchantment Table", Material.ENCHANTING_TABLE));
        registered.add(new BaseItem("Brewing Stand", Material.BREWING_STAND));
        registered.add(new BaseItem("Cauldron", Material.CAULDRON));
        registered.add(new BaseItem("End Portal Frame", Material.END_PORTAL_FRAME));
        registered.add(new BaseItem("End Stone", Material.END_STONE));
        registered.add(new BaseItem("Dragon Egg", Material.DRAGON_EGG));
        registered.add(new BaseItem("Redstone Lamp", Material.REDSTONE_LAMP));
        registered.add(new BaseItem("Emerald Ore", Material.EMERALD_ORE));
        registered.add(new BaseItem("Ender Chest", Material.ENDER_CHEST));
        registered.add(new BaseItem("Tripwire Hook", Material.TRIPWIRE_HOOK));
        registered.add(new BaseItem("Emerald Block", Material.EMERALD_BLOCK));
        registered.add(new BaseItem("Command Block", Material.COMMAND_BLOCK));
        registered.add(new BaseItem("Beacon", Material.BEACON));
        registered.add(new BaseItem("Cobblestone Wall", Material.COBBLESTONE_WALL));
        registered.add(new BaseItem("Mossy Cobblestone Wall", Material.MOSSY_COBBLESTONE_WALL));
        registered.add(new BaseItem("Flower Pot", Material.FLOWER_POT));
        registered.add(new BaseItem("Acacia Button", Material.ACACIA_BUTTON));
        registered.add(new BaseItem("Birch Button", Material.BIRCH_BUTTON));
        registered.add(new BaseItem("Jungle Button", Material.JUNGLE_BUTTON));
        registered.add(new BaseItem("Oak Button", Material.OAK_BUTTON));
        registered.add(new BaseItem("Spruce Button", Material.SPRUCE_BUTTON));
        registered.add(new BaseItem("Stone Button", Material.STONE_BUTTON));
        registered.add(new BaseItem("Skeleton Skull", Material.SKELETON_SKULL));
        registered.add(new BaseItem("Anvil", Material.ANVIL));
        registered.add(new BaseItem("Chipped Anvil", Material.CHIPPED_ANVIL));
        registered.add(new BaseItem("Damaged Anvil", Material.DAMAGED_ANVIL));
        registered.add(new BaseItem("Trapped Chest", Material.TRAPPED_CHEST));
        registered.add(new BaseItem("Iron Pressure Plate", Material.HEAVY_WEIGHTED_PRESSURE_PLATE));
        registered.add(new BaseItem("Weighted Iron Plate", Material.HEAVY_WEIGHTED_PRESSURE_PLATE));
        registered.add(new BaseItem("Weighted Gold Plate", Material.LIGHT_WEIGHTED_PRESSURE_PLATE));
        registered.add(new BaseItem("Comparator", Material.COMPARATOR));
        registered.add(new BaseItem("Daylight Sensor", Material.DAYLIGHT_DETECTOR));
        registered.add(new BaseItem("Redstone Block", Material.REDSTONE_BLOCK));
        registered.add(new BaseItem("Nether Quartz Ore", Material.NETHER_QUARTZ_ORE));
        registered.add(new BaseItem("Hopper", Material.HOPPER));
        registered.add(new BaseItem("Quartz Block", Material.QUARTZ_BLOCK));
        registered.add(new BaseItem("Chiseled Quartz Block", Material.CHISELED_QUARTZ_BLOCK));
        registered.add(new BaseItem("Pillar Quartz Block", Material.QUARTZ_PILLAR));
        registered.add(new BaseItem("Activator Rail", Material.ACTIVATOR_RAIL));
        registered.add(new BaseItem("Dropper", Material.DROPPER));

        // NOTE: Duplicates are for compatibility reasons, and should probably be removed
        // someday :tm:.
        registered.add(new BaseItem("White Stained Clay", Material.WHITE_TERRACOTTA));
        registered.add(new BaseItem("White Terracotta", Material.WHITE_TERRACOTTA));
        registered.add(new BaseItem("Orange Stained Clay", Material.ORANGE_TERRACOTTA));
        registered.add(new BaseItem("Orange Terracotta", Material.ORANGE_TERRACOTTA));
        registered.add(new BaseItem("Magenta Stained Clay", Material.MAGENTA_TERRACOTTA));
        registered.add(new BaseItem("Magenta Terracotta", Material.MAGENTA_TERRACOTTA));
        registered.add(new BaseItem("Light Blue Stained Clay", Material.LIGHT_BLUE_TERRACOTTA));
        registered.add(new BaseItem("Light Blue Terracotta", Material.LIGHT_BLUE_TERRACOTTA));
        registered.add(new BaseItem("Yellow Stained Clay", Material.YELLOW_TERRACOTTA));
        registered.add(new BaseItem("Yellow Terracotta", Material.YELLOW_TERRACOTTA));
        registered.add(new BaseItem("Lime Stained Clay", Material.LIME_TERRACOTTA));
        registered.add(new BaseItem("Lime Terracotta", Material.LIME_TERRACOTTA));
        registered.add(new BaseItem("Pink Stained Clay", Material.PINK_TERRACOTTA));
        registered.add(new BaseItem("Pink Terracotta", Material.PINK_TERRACOTTA));
        registered.add(new BaseItem("Gray Stained Clay", Material.GRAY_TERRACOTTA));
        registered.add(new BaseItem("Gray Terracotta", Material.GRAY_TERRACOTTA));
        registered.add(new BaseItem("Light Gray Stained Clay", Material.LIGHT_GRAY_TERRACOTTA));
        registered.add(new BaseItem("Light Gray Terracotta", Material.LIGHT_GRAY_TERRACOTTA));
        registered.add(new BaseItem("Cyan Stained Clay", Material.CYAN_TERRACOTTA));
        registered.add(new BaseItem("Cyan Terracotta", Material.CYAN_TERRACOTTA));
        registered.add(new BaseItem("Purple Stained Clay", Material.PURPLE_TERRACOTTA));
        registered.add(new BaseItem("Purple Terracotta", Material.PURPLE_TERRACOTTA));
        registered.add(new BaseItem("Blue Stained Clay", Material.BLUE_TERRACOTTA));
        registered.add(new BaseItem("Blue Terracotta", Material.BLUE_TERRACOTTA));
        registered.add(new BaseItem("Brown Stained Clay", Material.BROWN_TERRACOTTA));
        registered.add(new BaseItem("Brown Terracotta", Material.BROWN_TERRACOTTA));
        registered.add(new BaseItem("Green Stained Clay", Material.GREEN_TERRACOTTA));
        registered.add(new BaseItem("Green Terracotta", Material.GREEN_TERRACOTTA));
        registered.add(new BaseItem("Red Stained Clay", Material.RED_TERRACOTTA));
        registered.add(new BaseItem("Red Terracotta", Material.RED_TERRACOTTA));
        registered.add(new BaseItem("Black Stained Clay", Material.BLACK_TERRACOTTA));
        registered.add(new BaseItem("Black Terracotta", Material.BLACK_TERRACOTTA));

        registered.add(new BaseItem("Leaves", Material.OAK_LEAVES));
        registered.add(new BaseItem("Acacia Leaves", Material.ACACIA_LEAVES));
        registered.add(new BaseItem("Birch Leaves", Material.BIRCH_LEAVES));
        registered.add(new BaseItem("Dark Oak Leaves", Material.DARK_OAK_LEAVES));
        registered.add(new BaseItem("Jungle Leaves", Material.JUNGLE_LEAVES));
        registered.add(new BaseItem("Oak Leaves", Material.OAK_LEAVES));
        registered.add(new BaseItem("Spruce Leaves", Material.SPRUCE_LEAVES));

        registered.add(new BaseItem("Acacia Log", Material.ACACIA_LOG));
        registered.add(new BaseItem("Birch Log", Material.BIRCH_LOG));
        registered.add(new BaseItem("Dark Oak Log", Material.DARK_OAK_LOG));
        registered.add(new BaseItem("Jungle Log", Material.JUNGLE_LOG));
        registered.add(new BaseItem("Oak Log", Material.OAK_LOG));
        registered.add(new BaseItem("Spruce Log", Material.SPRUCE_LOG));

        registered.add(new BaseItem("Stripped Acacia Log", Material.STRIPPED_ACACIA_LOG));
        registered.add(new BaseItem("Stripped Birch Log", Material.STRIPPED_BIRCH_LOG));
        registered.add(new BaseItem("Stripped Dark Oak Log", Material.STRIPPED_DARK_OAK_LOG));
        registered.add(new BaseItem("Stripped Jungle Log", Material.STRIPPED_JUNGLE_LOG));
        registered.add(new BaseItem("Stripped Oak Log", Material.STRIPPED_OAK_LOG));
        registered.add(new BaseItem("Stripped Spruce Log", Material.STRIPPED_SPRUCE_LOG));

        registered.add(new BaseItem("Stripped Acacia Wood", Material.STRIPPED_ACACIA_WOOD));
        registered.add(new BaseItem("Stripped Birch Wood", Material.STRIPPED_BIRCH_WOOD));
        registered.add(new BaseItem("Stripped Dark Oak Wood", Material.STRIPPED_DARK_OAK_WOOD));
        registered.add(new BaseItem("Stripped Jungle Wood", Material.STRIPPED_JUNGLE_WOOD));
        registered.add(new BaseItem("Stripped Oak Wood", Material.STRIPPED_OAK_WOOD));
        registered.add(new BaseItem("Stripped Spruce Wood", Material.STRIPPED_SPRUCE_WOOD));

        registered.add(new BaseItem("Acacia Trapdoor", Material.ACACIA_TRAPDOOR));
        registered.add(new BaseItem("Birch Trapdoor", Material.BIRCH_TRAPDOOR));
        registered.add(new BaseItem("Dark Oak Trapdoor", Material.DARK_OAK_TRAPDOOR));
        registered.add(new BaseItem("Jungle Trapdoor", Material.JUNGLE_TRAPDOOR));
        registered.add(new BaseItem("Oak Trapdoor", Material.OAK_TRAPDOOR));
        registered.add(new BaseItem("Spruce Trapdoor", Material.SPRUCE_TRAPDOOR));

        registered.add(new BaseItem("Slime Block", Material.SLIME_BLOCK));
        registered.add(new BaseItem("Barrier", Material.BARRIER));
        registered.add(new BaseItem("Iron Trapdoor", Material.IRON_TRAPDOOR));
        registered.add(new BaseItem("Prismarine", Material.PRISMARINE));
        registered.add(new BaseItem("Prismarine Bricks", Material.PRISMARINE_BRICKS));
        registered.add(new BaseItem("Dark Prismarine", Material.DARK_PRISMARINE));
        registered.add(new BaseItem("Sea Lantern", Material.SEA_LANTERN));
        registered.add(new BaseItem("Hay Bale", Material.HAY_BLOCK));
        registered.add(new BaseItem("White Carpet", Material.WHITE_CARPET));
        registered.add(new BaseItem("Orange Carpet", Material.ORANGE_CARPET));
        registered.add(new BaseItem("Magenta Carpet", Material.MAGENTA_CARPET));
        registered.add(new BaseItem("Light Blue Carpet", Material.LIGHT_BLUE_CARPET));
        registered.add(new BaseItem("Yellow Carpet", Material.YELLOW_CARPET));
        registered.add(new BaseItem("Lime Carpet", Material.LIME_CARPET));
        registered.add(new BaseItem("Pink Carpet", Material.PINK_CARPET));
        registered.add(new BaseItem("Gray Carpet", Material.GRAY_CARPET));
        registered.add(new BaseItem("Light Gray Carpet", Material.LIGHT_GRAY_CARPET));
        registered.add(new BaseItem("Cyan Carpet", Material.CYAN_CARPET));
        registered.add(new BaseItem("Purple Carpet", Material.PURPLE_CARPET));
        registered.add(new BaseItem("Blue Carpet", Material.BLUE_CARPET));
        registered.add(new BaseItem("Brown Carpet", Material.BROWN_CARPET));
        registered.add(new BaseItem("Green Carpet", Material.GREEN_CARPET));
        registered.add(new BaseItem("Red Carpet", Material.RED_CARPET));
        registered.add(new BaseItem("Black Carpet", Material.BLACK_CARPET));
        registered.add(new BaseItem("Hardened Clay", Material.TERRACOTTA));
        registered.add(new BaseItem("Coal Block", Material.COAL_BLOCK));
        registered.add(new BaseItem("Packed Ice", Material.PACKED_ICE));
        registered.add(new BaseItem("Sun Flower", Material.SUNFLOWER));
        registered.add(new BaseItem("Lilac", Material.LILAC));
        registered.add(new BaseItem("Double Tall Grass", Material.TALL_GRASS));
        registered.add(new BaseItem("Tall Fern", Material.LARGE_FERN));
        registered.add(new BaseItem("Rose Bush", Material.ROSE_BUSH));
        registered.add(new BaseItem("Peony", Material.PEONY));
        registered.add(new BaseItem("Red Sandstone", Material.RED_SANDSTONE));
        registered.add(new BaseItem("Chiseled Red Sandstone", Material.CHISELED_RED_SANDSTONE));
        registered.add(new BaseItem("Smooth Red Sandstone", Material.SMOOTH_RED_SANDSTONE));
        registered.add(new BaseItem("Red Sandstone Stairs", Material.RED_SANDSTONE_STAIRS));
        registered.add(new BaseItem("Red Sandstone Slab", Material.RED_SANDSTONE_SLAB));
        registered.add(new BaseItem("Spruce Fence", Material.SPRUCE_FENCE));
        registered.add(new BaseItem("Birch Fence", Material.BIRCH_FENCE));
        registered.add(new BaseItem("Jungle Fence", Material.JUNGLE_FENCE));
        registered.add(new BaseItem("Dark Oak Fence", Material.DARK_OAK_FENCE));
        registered.add(new BaseItem("Acacia Fence", Material.ACACIA_FENCE));
        registered.add(new BaseItem("Spruce Door", Material.SPRUCE_DOOR));
        registered.add(new BaseItem("Birch Door", Material.BIRCH_DOOR));
        registered.add(new BaseItem("Jungle Door", Material.JUNGLE_DOOR));
        registered.add(new BaseItem("Acacia Door", Material.ACACIA_DOOR));
        registered.add(new BaseItem("Dark Oak Door", Material.DARK_OAK_DOOR));
        registered.add(new BaseItem("End Rod", Material.END_ROD));
        registered.add(new BaseItem("Chorus Plant", Material.CHORUS_PLANT));
        registered.add(new BaseItem("Chorus Flower", Material.CHORUS_FLOWER));
        registered.add(new BaseItem("Purpur Block", Material.PURPUR_BLOCK));
        registered.add(new BaseItem("Purpur Pillar", Material.PURPUR_PILLAR));
        registered.add(new BaseItem("Purpur Stairs", Material.PURPUR_STAIRS));
        registered.add(new BaseItem("Purpur Slab", Material.PURPUR_SLAB));
        registered.add(new BaseItem("End Stone Brick", Material.END_STONE_BRICKS));
        registered.add(new BaseItem("Grass Path", Material.GRASS_PATH));
        registered.add(new BaseItem("Repeating Command Block", Material.REPEATING_COMMAND_BLOCK));
        registered.add(new BaseItem("Chain Command Block", Material.CHAIN_COMMAND_BLOCK));
        registered.add(new BaseItem("Magma Block", Material.MAGMA_BLOCK));
        registered.add(new BaseItem("Nether Wart Block", Material.NETHER_WART_BLOCK));
        registered.add(new BaseItem("Red Nether Brick", Material.RED_NETHER_BRICKS));
        registered.add(new BaseItem("Bone Block", Material.BONE_BLOCK));
        registered.add(new BaseItem("Structure Void", Material.STRUCTURE_VOID));
        registered.add(new BaseItem("Observer", Material.OBSERVER));
        registered.add(new BaseItem("White Shulker Box", Material.WHITE_SHULKER_BOX));
        registered.add(new BaseItem("Orange Shulker Box", Material.ORANGE_SHULKER_BOX));
        registered.add(new BaseItem("Magenta Shulker Box", Material.MAGENTA_SHULKER_BOX));
        registered.add(new BaseItem("Light Blue Shulker Box", Material.LIGHT_BLUE_SHULKER_BOX));
        registered.add(new BaseItem("Yellow Shulker Box", Material.YELLOW_SHULKER_BOX));
        registered.add(new BaseItem("Lime Shulker Box", Material.LIME_SHULKER_BOX));
        registered.add(new BaseItem("Pink Shulker Box", Material.PINK_SHULKER_BOX));
        registered.add(new BaseItem("Gray Shulker Box", Material.GRAY_SHULKER_BOX));
        registered.add(new BaseItem("Light Gray Shulker Box", Material.LIGHT_GRAY_SHULKER_BOX));
        registered.add(new BaseItem("Cyan Shulker Box", Material.CYAN_SHULKER_BOX));
        registered.add(new BaseItem("Purple Shulker Box", Material.PURPLE_SHULKER_BOX));
        registered.add(new BaseItem("Blue Shulker Box", Material.BLUE_SHULKER_BOX));
        registered.add(new BaseItem("Brown Shulker Box", Material.BROWN_SHULKER_BOX));
        registered.add(new BaseItem("Green Shulker Box", Material.GREEN_SHULKER_BOX));
        registered.add(new BaseItem("Red Shulker Box", Material.RED_SHULKER_BOX));
        registered.add(new BaseItem("Black Shulker Box", Material.BLACK_SHULKER_BOX));
        registered.add(new BaseItem("White Glazed Terracotta", Material.WHITE_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Orange Glazed Terracotta", Material.ORANGE_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Magenta Glazed Terracotta", Material.MAGENTA_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Light Blue Glazed Terracotta", Material.LIGHT_BLUE_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Yellow Glazed Terracotta", Material.YELLOW_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Lime Glazed Terracotta", Material.LIME_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Pink Glazed Terracotta", Material.PINK_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Gray Glazed Terracotta", Material.GRAY_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Light Gray Glazed Terracotta", Material.LIGHT_GRAY_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Cyan Glazed Terracotta", Material.CYAN_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Purple Glazed Terracotta", Material.PURPLE_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Blue Glazed Terracotta", Material.BLUE_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Brown Glazed Terracotta", Material.BROWN_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Green Glazed Terracotta", Material.GREEN_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Red Glazed Terracotta", Material.RED_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("Black Glazed Terracotta", Material.BLACK_GLAZED_TERRACOTTA));
        registered.add(new BaseItem("White Concrete", Material.WHITE_CONCRETE));
        registered.add(new BaseItem("Orange Concrete", Material.ORANGE_CONCRETE));
        registered.add(new BaseItem("Magenta Concrete", Material.MAGENTA_CONCRETE));
        registered.add(new BaseItem("Light Blue Concrete", Material.LIGHT_BLUE_CONCRETE));
        registered.add(new BaseItem("Yellow Concrete", Material.YELLOW_CONCRETE));
        registered.add(new BaseItem("Lime Concrete", Material.LIME_CONCRETE));
        registered.add(new BaseItem("Pink Concrete", Material.PINK_CONCRETE));
        registered.add(new BaseItem("Gray Concrete", Material.GRAY_CONCRETE));
        registered.add(new BaseItem("Light Gray Concrete", Material.LIGHT_GRAY_CONCRETE));
        registered.add(new BaseItem("Cyan Concrete", Material.CYAN_CONCRETE));
        registered.add(new BaseItem("Purple Concrete", Material.PURPLE_CONCRETE));
        registered.add(new BaseItem("Blue Concrete", Material.BLUE_CONCRETE));
        registered.add(new BaseItem("Brown Concrete", Material.BROWN_CONCRETE));
        registered.add(new BaseItem("Green Concrete", Material.GREEN_CONCRETE));
        registered.add(new BaseItem("Red Concrete", Material.RED_CONCRETE));
        registered.add(new BaseItem("Black Concrete", Material.BLACK_CONCRETE));
        registered.add(new BaseItem("White Concrete Powder", Material.WHITE_CONCRETE_POWDER));
        registered.add(new BaseItem("Orange Concrete Powder", Material.ORANGE_CONCRETE_POWDER));
        registered.add(new BaseItem("Magenta Concrete Powder", Material.MAGENTA_CONCRETE_POWDER));
        registered.add(new BaseItem("Light Blue Concrete Powder", Material.LIGHT_BLUE_CONCRETE_POWDER));
        registered.add(new BaseItem("Yellow Concrete Powder", Material.YELLOW_CONCRETE_POWDER));
        registered.add(new BaseItem("Lime Concrete Powder", Material.LIME_CONCRETE_POWDER));
        registered.add(new BaseItem("Pink Concrete Powder", Material.PINK_CONCRETE_POWDER));
        registered.add(new BaseItem("Gray Concrete Powder", Material.GRAY_CONCRETE_POWDER));
        registered.add(new BaseItem("Light Gray Concrete Powder", Material.LIGHT_GRAY_CONCRETE_POWDER));
        registered.add(new BaseItem("Cyan Concrete Powder", Material.CYAN_CONCRETE_POWDER));
        registered.add(new BaseItem("Purple Concrete Powder", Material.PURPLE_CONCRETE_POWDER));
        registered.add(new BaseItem("Blue Concrete Powder", Material.BLUE_CONCRETE_POWDER));
        registered.add(new BaseItem("Brown Concrete Powder", Material.BROWN_CONCRETE_POWDER));
        registered.add(new BaseItem("Green Concrete Powder", Material.GREEN_CONCRETE_POWDER));
        registered.add(new BaseItem("Red Concrete Powder", Material.RED_CONCRETE_POWDER));
        registered.add(new BaseItem("Black Concrete Powder", Material.BLACK_CONCRETE_POWDER));
        registered.add(new BaseItem("Structure Block", Material.STRUCTURE_BLOCK));

        registered.add(new BaseItem("Iron Shovel", Material.IRON_SHOVEL));
        registered.add(new BaseItem("Iron Pickaxe", Material.IRON_PICKAXE));
        registered.add(new BaseItem("Iron Axe", Material.IRON_AXE));
        registered.add(new BaseItem("Flint and Steel", Material.FLINT_AND_STEEL));
        registered.add(new BaseItem("Apple", Material.APPLE));
        registered.add(new BaseItem("Bow", Material.BOW));
        registered.add(new BaseItem("ARROW", Material.ARROW));
        registered.add(new BaseItem("Coal", Material.COAL));
        registered.add(new BaseItem("Charcoal", Material.CHARCOAL));
        registered.add(new BaseItem("Diamond", Material.DIAMOND));
        registered.add(new BaseItem("Iron Ingot", Material.IRON_INGOT));
        registered.add(new BaseItem("Gold Ingot", Material.GOLD_INGOT));
        registered.add(new BaseItem("Iron Sword", Material.IRON_SWORD));
        registered.add(new BaseItem("Wood Sword", Material.WOODEN_SWORD));
        registered.add(new BaseItem("Wood Axe", Material.WOODEN_AXE));
        registered.add(new BaseItem("Stone Sword", Material.STONE_SWORD));
        registered.add(new BaseItem("Stone Shovel", Material.STONE_SHOVEL));
        registered.add(new BaseItem("Stone Pickaxe", Material.STONE_PICKAXE));
        registered.add(new BaseItem("Stone Axe", Material.STONE_AXE));
        registered.add(new BaseItem("Diamond Sword", Material.DIAMOND_SWORD));
        registered.add(new BaseItem("Diamond Shovel", Material.DIAMOND_SHOVEL));
        registered.add(new BaseItem("Diamond Pickaxe", Material.DIAMOND_PICKAXE));
        registered.add(new BaseItem("Diamond Axe", Material.DIAMOND_AXE));
        registered.add(new BaseItem("Stick", Material.STICK));
        registered.add(new BaseItem("Bowl", Material.BOWL));
        registered.add(new BaseItem("Mushroom Stew", Material.MUSHROOM_STEW));
        registered.add(new BaseItem("Gold Sword", Material.GOLDEN_SWORD));
        registered.add(new BaseItem("Gold Shovel", Material.GOLDEN_SHOVEL));
        registered.add(new BaseItem("Gold Axe", Material.GOLDEN_AXE));
        registered.add(new BaseItem("String", Material.STRING));
        registered.add(new BaseItem("Feather", Material.FEATHER));
        registered.add(new BaseItem("Gunpowder", Material.GUNPOWDER));
        registered.add(new BaseItem("Wooden Hoe", Material.WOODEN_HOE));
        registered.add(new BaseItem("Stone Hoe", Material.STONE_HOE));
        registered.add(new BaseItem("Iron Hoe", Material.IRON_HOE));
        registered.add(new BaseItem("Diamond Hoe", Material.DIAMOND_HOE));
        registered.add(new BaseItem("Gold Hoe", Material.GOLDEN_HOE));
        registered.add(new BaseItem("Wheat Seeds", Material.WHEAT_SEEDS));
        registered.add(new BaseItem("Wheat", Material.WHEAT));
        registered.add(new BaseItem("Bread", Material.BREAD));
        registered.add(new BaseItem("Leather Cap", Material.LEATHER_HELMET));
        registered.add(new BaseItem("Leather Tunic", Material.LEATHER_CHESTPLATE));
        registered.add(new BaseItem("Leather Pants", Material.LEATHER_LEGGINGS));
        registered.add(new BaseItem("Leather Boots", Material.LEATHER_BOOTS));
        registered.add(new BaseItem("Chainmail Cap", Material.CHAINMAIL_HELMET));
        registered.add(new BaseItem("Chainmail Tunic", Material.CHAINMAIL_CHESTPLATE));
        registered.add(new BaseItem("Chainmail Pants", Material.CHAINMAIL_LEGGINGS));
        registered.add(new BaseItem("Chainmail Boots", Material.CHAINMAIL_BOOTS));
        registered.add(new BaseItem("Iron Cap", Material.IRON_HELMET));
        registered.add(new BaseItem("Iron Tunic", Material.IRON_CHESTPLATE));
        registered.add(new BaseItem("Iron Pants", Material.IRON_LEGGINGS));
        registered.add(new BaseItem("Iron Boots", Material.IRON_BOOTS));
        registered.add(new BaseItem("Diamond Cap", Material.DIAMOND_HELMET));
        registered.add(new BaseItem("Diamond Tunic", Material.DIAMOND_CHESTPLATE));
        registered.add(new BaseItem("Diamond Pants", Material.DIAMOND_LEGGINGS));
        registered.add(new BaseItem("Diamond boots", Material.DIAMOND_BOOTS));
        registered.add(new BaseItem("Flint", Material.FLINT));
        registered.add(new BaseItem("Raw Pork", Material.PORKCHOP));
        registered.add(new BaseItem("Grilled Pork", Material.COOKED_PORKCHOP));
        registered.add(new BaseItem("Painting", Material.PAINTING));
        registered.add(new BaseItem("Golden Apple", Material.GOLDEN_APPLE));
        registered.add(new BaseItem("Enchanted Golden Apple", Material.ENCHANTED_GOLDEN_APPLE));
        registered.add(new BaseItem("Bucket", Material.BUCKET));
        registered.add(new BaseItem("Water Bucket", Material.WATER_BUCKET));
        registered.add(new BaseItem("Lava Bucket", Material.LAVA_BUCKET));
        registered.add(new BaseItem("Minecart", Material.MINECART));
        registered.add(new BaseItem("Saddle", Material.SADDLE));
        registered.add(new BaseItem("Iron Door", Material.IRON_DOOR));
        registered.add(new BaseItem("Redstone", Material.REDSTONE));
        registered.add(new BaseItem("Snowball", Material.SNOWBALL));
        registered.add(new BaseItem("Boat", Material.OAK_BOAT));
        registered.add(new BaseItem("Oak Boat", Material.OAK_BOAT));
        registered.add(new BaseItem("Acacia Boat", Material.ACACIA_BOAT));
        registered.add(new BaseItem("Birch Boat", Material.BIRCH_BOAT));
        registered.add(new BaseItem("Dark Oak Boat", Material.DARK_OAK_BOAT));
        registered.add(new BaseItem("Jungle Boat", Material.JUNGLE_BOAT));
        registered.add(new BaseItem("Spruce Boat", Material.SPRUCE_BOAT));
        registered.add(new BaseItem("Leather", Material.LEATHER));
        registered.add(new BaseItem("Milk Bucket", Material.MILK_BUCKET));
        registered.add(new BaseItem("Brick", Material.BRICK));
        registered.add(new BaseItem("Clay Ball", Material.CLAY_BALL));
        registered.add(new BaseItem("Sugar Canes", Material.SUGAR_CANE));
        registered.add(new BaseItem("Paper", Material.PAPER));
        registered.add(new BaseItem("Book", Material.BOOK));
        registered.add(new BaseItem("Slimeball", Material.SLIME_BALL));
        registered.add(new BaseItem("Chest Minecart", Material.CHEST_MINECART));
        registered.add(new BaseItem("Furnace Minecart", Material.FURNACE_MINECART));
        registered.add(new BaseItem("Egg", Material.EGG));
        registered.add(new BaseItem("Compass", Material.COMPASS));
        registered.add(new BaseItem("Fishing Rod", Material.FISHING_ROD));
        registered.add(new BaseItem("Clock", Material.CLOCK));
        registered.add(new BaseItem("Glowstone Dust", Material.GLOWSTONE_DUST));

        registered.add(new BaseItem("Raw Cod", Material.COD));
        registered.add(new BaseItem("Raw Salmon", Material.SALMON));
        registered.add(new BaseItem("Tropical Fish", Material.TROPICAL_FISH));
        registered.add(new BaseItem("Puffer Fish", Material.PUFFERFISH));
        registered.add(new BaseItem("Cooked Cod", Material.COOKED_COD));
        registered.add(new BaseItem("Cooked Salmon", Material.COOKED_SALMON));
        registered.add(new BaseItem("Dried Kelp", Material.DRIED_KELP));
        registered.add(new BaseItem("Kelp", Material.KELP));

        registered.add(new BaseItem("Ink Sac", Material.INK_SAC));
        registered.add(new BaseItem("Rose Red", Material.RED_DYE));
        registered.add(new BaseItem("Red Dye", Material.RED_DYE));
        registered.add(new BaseItem("Cactus Green", Material.GREEN_DYE));
        registered.add(new BaseItem("Green Dye", Material.GREEN_DYE));

        registered.add(new BaseItem("Cocoa Beans", Material.COCOA_BEANS));
        registered.add(new BaseItem("Lapis Lazuli", Material.LAPIS_LAZULI));
        registered.add(new BaseItem("Purple Dye", Material.PURPLE_DYE));
        registered.add(new BaseItem("Cyan Dye", Material.CYAN_DYE));
        registered.add(new BaseItem("Light Gray Dye", Material.LIGHT_GRAY_DYE));
        registered.add(new BaseItem("Gray Dye", Material.GRAY_DYE));
        registered.add(new BaseItem("Pink Dye", Material.PINK_DYE));
        registered.add(new BaseItem("Lime Dye", Material.LIME_DYE));
        registered.add(new BaseItem("Dandelion Yellow", Material.YELLOW_DYE));
        registered.add(new BaseItem("Yellow Dye", Material.YELLOW_DYE));
        registered.add(new BaseItem("Light Blue Dye", Material.LIGHT_BLUE_DYE));
        registered.add(new BaseItem("Magenta Dye", Material.MAGENTA_DYE));
        registered.add(new BaseItem("Orange Dye", Material.ORANGE_DYE));
        registered.add(new BaseItem("Bone Meal", Material.BONE_MEAL));
        registered.add(new BaseItem("Bone", Material.BONE));
        registered.add(new BaseItem("Sugar", Material.SUGAR));
        registered.add(new BaseItem("Cake", Material.CAKE));
        registered.add(new BaseItem("Cookie", Material.COOKIE));
        registered.add(new BaseItem("Map", Material.MAP));
        registered.add(new BaseItem("Shears", Material.SHEARS));
        registered.add(new BaseItem("Melon", Material.MELON));
        registered.add(new BaseItem("Pumpkin Seeds", Material.PUMPKIN_SEEDS));
        registered.add(new BaseItem("Melon Seeds", Material.MELON_SEEDS));
        registered.add(new BaseItem("Raw Beef", Material.BEEF));
        registered.add(new BaseItem("Steak", Material.COOKED_BEEF));
        registered.add(new BaseItem("Raw Chicken", Material.CHICKEN));
        registered.add(new BaseItem("Cooked Chicken", Material.COOKED_CHICKEN));
        registered.add(new BaseItem("Rotten Flesh", Material.ROTTEN_FLESH));
        registered.add(new BaseItem("Ender Pearl", Material.ENDER_PEARL));
        registered.add(new BaseItem("Blaze Rod", Material.BLAZE_ROD));
        registered.add(new BaseItem("Ghast Tear", Material.GHAST_TEAR));
        registered.add(new BaseItem("Gold Nugget", Material.GOLD_NUGGET));
        registered.add(new BaseItem("Potion", Material.POTION));
        registered.add(new BaseItem("Glass Bottle", Material.GLASS_BOTTLE));
        registered.add(new BaseItem("Spider Eye", Material.SPIDER_EYE));
        registered.add(new BaseItem("Fermented Spider Eye", Material.FERMENTED_SPIDER_EYE));
        registered.add(new BaseItem("Blaze Powder", Material.BLAZE_POWDER));
        registered.add(new BaseItem("Magma Cream", Material.MAGMA_CREAM));
        registered.add(new BaseItem("Brewing Stand", Material.BREWING_STAND));
        registered.add(new BaseItem("Eye of Ender", Material.ENDER_EYE));
        registered.add(new BaseItem("Glistening Melon", Material.GLISTERING_MELON_SLICE));
        registered.add(new BaseItem("Spawn Elder Guardian", Material.ELDER_GUARDIAN_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Wither Skeleton", Material.WITHER_SKELETON_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Stray", Material.STRAY_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Husk", Material.HUSK_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Zombie Villager", Material.ZOMBIE_VILLAGER_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Skeleton Horse", Material.SKELETON_HORSE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Zombie Horse", Material.ZOMBIE_HORSE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Donkey", Material.DONKEY_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Mule", Material.MULE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Evoker", Material.EVOKER_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Vex", Material.VEX_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Vindicator", Material.VINDICATOR_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Creeper", Material.CREEPER_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Skeleton", Material.SKELETON_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Spider", Material.SPIDER_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Zombie", Material.ZOMBIE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Slime", Material.SLIME_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Ghast", Material.GHAST_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Zombie Pigman", Material.ZOMBIE_PIGMAN_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Enderman", Material.ENDERMAN_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Cave Spider", Material.CAVE_SPIDER_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Silverfish", Material.SILVERFISH_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Blaze", Material.BLAZE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Magma Cube", Material.MAGMA_CUBE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Bat", Material.BAT_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Witch", Material.WITCH_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Endermite", Material.ENDERMITE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Guardian", Material.GUARDIAN_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Shulker", Material.SHULKER_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Pig", Material.PIG_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Sheep", Material.SHEEP_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Cow", Material.COW_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Chicken", Material.CHICKEN_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Squid", Material.SQUID_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Wolf", Material.WOLF_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Mooshroom", Material.MOOSHROOM_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Ocelot", Material.OCELOT_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Horse", Material.HORSE_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Rabbit", Material.RABBIT_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Polar Bear", Material.POLAR_BEAR_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Llama", Material.LLAMA_SPAWN_EGG));
        registered.add(new BaseItem("Spawn Villager", Material.VILLAGER_SPAWN_EGG));
        registered.add(new BaseItem("Bottle 'o Enchanting", Material.EXPERIENCE_BOTTLE));
        registered.add(new BaseItem("Fire Charge", Material.FIRE_CHARGE));
        registered.add(new BaseItem("Book and Quill", Material.WRITABLE_BOOK));
        registered.add(new BaseItem("Written Book", Material.WRITTEN_BOOK));
        registered.add(new BaseItem("Emerald", Material.EMERALD));
        registered.add(new BaseItem("Item Frame", Material.ITEM_FRAME));
        registered.add(new BaseItem("Carrot", Material.CARROT));
        registered.add(new BaseItem("Blue Ice", Material.BLUE_ICE));
        registered.add(new BaseItem("Potato", Material.POTATO));
        registered.add(new BaseItem("Baked Potato", Material.BAKED_POTATO));
        registered.add(new BaseItem("Poisonous Potato", Material.POISONOUS_POTATO));
        registered.add(new BaseItem("Empty Map", Material.MAP));
        registered.add(new BaseItem("Golden Carrot", Material.GOLDEN_CARROT));
        registered.add(new BaseItem("Wither Skull", Material.WITHER_SKELETON_SKULL));
        registered.add(new BaseItem("Zombie Skull", Material.ZOMBIE_HEAD));
        registered.add(new BaseItem("Player Skull", Material.PLAYER_HEAD));
        registered.add(new BaseItem("Creeper Skull", Material.CREEPER_HEAD));
        registered.add(new BaseItem("Dragon Skull", Material.DRAGON_HEAD));
        registered.add(new BaseItem("Carrot on a Stick", Material.CARROT_ON_A_STICK));
        registered.add(new BaseItem("Nether Star", Material.NETHER_STAR));
        registered.add(new BaseItem("Pumpkin Pie", Material.PUMPKIN_PIE));
        registered.add(new BaseItem("Firework Rocket", Material.FIREWORK_ROCKET));
        registered.add(new BaseItem("Firework Star", Material.FIREWORK_STAR));
        registered.add(new BaseItem("Enchanted Book", Material.ENCHANTED_BOOK));
        registered.add(new BaseItem("Nether Brick", Material.NETHER_BRICK));
        registered.add(new BaseItem("Raw Rabbit", Material.RABBIT));
        registered.add(new BaseItem("Cooked Rabbit", Material.COOKED_RABBIT));
        registered.add(new BaseItem("Rabbit Foot", Material.RABBIT_FOOT));
        registered.add(new BaseItem("Rabbit Hide", Material.RABBIT_HIDE));
        registered.add(new BaseItem("Armor Stand", Material.ARMOR_STAND));
        registered.add(new BaseItem("Iron Horse Armor", Material.IRON_HORSE_ARMOR));
        registered.add(new BaseItem("Gold Horse Armor", Material.IRON_HORSE_ARMOR));
        registered.add(new BaseItem("Diamond Horse Armor", Material.DIAMOND_HORSE_ARMOR));
        registered.add(new BaseItem("Lead", Material.LEAD));
        registered.add(new BaseItem("Name Tag", Material.NAME_TAG));
        registered.add(new BaseItem("Minecart with Command Block", Material.COMMAND_BLOCK_MINECART));
        registered.add(new BaseItem("Raw Mutton", Material.MUTTON));
        registered.add(new BaseItem("Cooked Mutton", Material.COOKED_MUTTON));
        registered.add(new BaseItem("White Banner", Material.WHITE_BANNER));
        registered.add(new BaseItem("Orange Banner", Material.ORANGE_BANNER));
        registered.add(new BaseItem("Magenta Banner", Material.MAGENTA_BANNER));
        registered.add(new BaseItem("Light Blue Banner", Material.LIGHT_BLUE_BANNER));
        registered.add(new BaseItem("Yellow Banner", Material.YELLOW_BANNER));
        registered.add(new BaseItem("Lime Banner", Material.LIME_BANNER));
        registered.add(new BaseItem("Pink Banner", Material.PINK_BANNER));
        registered.add(new BaseItem("Gray Banner", Material.GRAY_BANNER));
        registered.add(new BaseItem("Light Gray Banner", Material.LIGHT_GRAY_BANNER));
        registered.add(new BaseItem("Cyan Banner", Material.CYAN_BANNER));
        registered.add(new BaseItem("Purple Banner", Material.PURPLE_BANNER));
        registered.add(new BaseItem("Blue Banner", Material.BLUE_BANNER));
        registered.add(new BaseItem("Brown Banner", Material.BROWN_BANNER));
        registered.add(new BaseItem("Green Banner", Material.GREEN_BANNER));
        registered.add(new BaseItem("Red Banner", Material.RED_BANNER));
        registered.add(new BaseItem("Black Banner", Material.BLACK_BANNER));
        registered.add(new BaseItem("Beetroot", Material.BEETROOT));
        registered.add(new BaseItem("Beetroot Seeds", Material.BEETROOT_SEEDS));
        registered.add(new BaseItem("Beetroot Soup", Material.BEETROOT_SOUP));
        registered.add(new BaseItem("Dragon Breath", Material.DRAGON_BREATH));
        registered.add(new BaseItem("Splash Potion", Material.SPLASH_POTION));
        registered.add(new BaseItem("Spectral Arrow", Material.SPECTRAL_ARROW));
        registered.add(new BaseItem("Tipped Arrow", Material.TIPPED_ARROW));
        registered.add(new BaseItem("Lingering Potion", Material.LINGERING_POTION));
        registered.add(new BaseItem("Shield", Material.SHIELD));
        registered.add(new BaseItem("Elytra", Material.ELYTRA));
        registered.add(new BaseItem("Totem of Undying", Material.TOTEM_OF_UNDYING));
        registered.add(new BaseItem("Shulker Shell", Material.SHULKER_SHELL));
        registered.add(new BaseItem("Iron Nugget", Material.IRON_NUGGET));
        registered.add(new BaseItem("Disc 13", Material.MUSIC_DISC_13));
        registered.add(new BaseItem("Disc Cat", Material.MUSIC_DISC_CAT));
        registered.add(new BaseItem("Disc Blocks", Material.MUSIC_DISC_BLOCKS));
        registered.add(new BaseItem("Disc Chirp", Material.MUSIC_DISC_CHIRP));
        registered.add(new BaseItem("Disc Far", Material.MUSIC_DISC_FAR));
        registered.add(new BaseItem("Disc Mall", Material.MUSIC_DISC_MALL));
        registered.add(new BaseItem("Disc Mellohi", Material.MUSIC_DISC_MELLOHI));
        registered.add(new BaseItem("Disc Stal", Material.MUSIC_DISC_STAL));
        registered.add(new BaseItem("Disc Strad", Material.MUSIC_DISC_STRAD));
        registered.add(new BaseItem("Disc Ward", Material.MUSIC_DISC_WARD));
        registered.add(new BaseItem("Disc 11", Material.MUSIC_DISC_11));
        registered.add(new BaseItem("Disc Wait", Material.MUSIC_DISC_WAIT));
        registered.add(new BaseItem("Brain Coral", Material.BRAIN_CORAL));
        registered.add(new BaseItem("Brain Coral Block", Material.BRAIN_CORAL));
        registered.add(new BaseItem("Brain Coral Fan", Material.BRAIN_CORAL_FAN));
        registered.add(new BaseItem("Bubble Coral", Material.BUBBLE_CORAL));
        registered.add(new BaseItem("Bubble Coral Block", Material.BUBBLE_CORAL_BLOCK));
        registered.add(new BaseItem("Bubble Coral Fan", Material.BUBBLE_CORAL_FAN));
        registered.add(new BaseItem("Carved Pumpkin", Material.CARVED_PUMPKIN));
        registered.add(new BaseItem("Chorus Fruit", Material.CHORUS_FRUIT));
        registered.add(new BaseItem("Cod Bucket", Material.COD_BUCKET));
        registered.add(new BaseItem("Cut Red Sandstone", Material.CUT_RED_SANDSTONE));
        registered.add(new BaseItem("Cut Sandstone", Material.CUT_SANDSTONE));
        registered.add(new BaseItem("Cyan Bed", Material.CYAN_BED));
        registered.add(new BaseItem("Magenta Bed", Material.MAGENTA_BED));
        registered.add(new BaseItem("Dark Oak Button", Material.DARK_OAK_BUTTON));
        registered.add(new BaseItem("Dark Oak Sapling", Material.DARK_OAK_SAPLING));
        registered.add(new BaseItem("Dark Oak Trapdoor", Material.DARK_OAK_TRAPDOOR));
        registered.add(new BaseItem("Dead Brain Coral Block", Material.DEAD_BRAIN_CORAL_BLOCK));
        registered.add(new BaseItem("Dead Brain Coral Fan", Material.DEAD_BRAIN_CORAL_FAN));
        registered.add(new BaseItem("Dead Fire Coral Block", Material.DEAD_FIRE_CORAL_BLOCK));
        registered.add(new BaseItem("Dead Fire Coral Fan", Material.DEAD_FIRE_CORAL_FAN));
        registered.add(new BaseItem("Dead Horn Coral Block", Material.DEAD_HORN_CORAL_BLOCK));
        registered.add(new BaseItem("Dead Horn Coral Fan", Material.DEAD_HORN_CORAL_FAN));
        registered.add(new BaseItem("Dead Tube Coral Block", Material.DEAD_TUBE_CORAL_BLOCK));
        registered.add(new BaseItem("Dead Tube Coral Fan", Material.DEAD_TUBE_CORAL_FAN));
        registered.add(new BaseItem("Diamond Block", Material.DIAMOND_BLOCK));
        registered.add(new BaseItem("Dolphin Spawn Egg", Material.DOLPHIN_SPAWN_EGG));
        registered.add(new BaseItem("Dried Kelp Block", Material.DRIED_KELP_BLOCK));
        registered.add(new BaseItem("Drowned Spawn Egg", Material.DROWNED_SPAWN_EGG));
        registered.add(new BaseItem("Fire Coral Block", Material.FIRE_CORAL_BLOCK));
        registered.add(new BaseItem("Fire Coral Fan", Material.FIRE_CORAL_FAN));
        registered.add(new BaseItem("Gold Boots", Material.GOLDEN_BOOTS));
        registered.add(new BaseItem("Gold Chestplate", Material.GOLDEN_CHESTPLATE));
        registered.add(new BaseItem("Gold Helmet", Material.GOLDEN_HELMET));
        registered.add(new BaseItem("Gold Horse Armor", Material.GOLDEN_HORSE_ARMOR));
        registered.add(new BaseItem("Gold Pants", Material.GOLDEN_LEGGINGS));
        registered.add(new BaseItem("Gold Pickaxe", Material.GOLDEN_PICKAXE));
        registered.add(new BaseItem("Grass Block", Material.GRASS_BLOCK));
        registered.add(new BaseItem("Heart of the Sea", Material.HEART_OF_THE_SEA));
        registered.add(new BaseItem("Hopper Minecart", Material.HOPPER_MINECART));
        registered.add(new BaseItem("Horn Coral", Material.HORN_CORAL));
        registered.add(new BaseItem("Horn Coral Block", Material.HORN_CORAL_BLOCK));
        registered.add(new BaseItem("Horn Coral Fan", Material.HORN_CORAL_FAN));
        registered.add(new BaseItem("Jungle Trapdoor", Material.JUNGLE_TRAPDOOR));
        registered.add(new BaseItem("Melon Slice", Material.MELON_SLICE));
        registered.add(new BaseItem("Nautilus Shell", Material.NAUTILUS_SHELL));
        registered.add(new BaseItem("Nether Bricks", Material.NETHER_BRICKS));
        registered.add(new BaseItem("Orange Bed", Material.ORANGE_BED));
        registered.add(new BaseItem("Parrot Spawn Egg", Material.PARROT_SPAWN_EGG));
        registered.add(new BaseItem("Phantom Membrane", Material.PHANTOM_MEMBRANE));
        registered.add(new BaseItem("Phantom Spawn Egg", Material.PHANTOM_SPAWN_EGG));
        registered.add(new BaseItem("Puffer Fish Bucket", Material.PUFFERFISH_BUCKET));
        registered.add(new BaseItem("Puffer Fish Spawn Egg", Material.PUFFERFISH_SPAWN_EGG));
        registered.add(new BaseItem("Quartz Pillar", Material.QUARTZ_PILLAR));
        registered.add(new BaseItem("Quartz", Material.QUARTZ));
        registered.add(new BaseItem("Rabbit Stew", Material.RABBIT_STEW));
        registered.add(new BaseItem("Red Stained Glass Pane", Material.RED_STAINED_GLASS_PANE));
        registered.add(new BaseItem("Salmon Bucket", Material.SALMON_BUCKET));
        registered.add(new BaseItem("Salmon Spawn Egg", Material.SALMON_SPAWN_EGG));
        registered.add(new BaseItem("Wandering Trader Spawn Egg", Material.WANDERING_TRADER_SPAWN_EGG));
        registered.add(new BaseItem("Fox Spawn Egg", Material.FOX_SPAWN_EGG));
        registered.add(new BaseItem("Panda Spawn Egg", Material.PANDA_SPAWN_EGG));
        registered.add(new BaseItem("Pillager Spawn Egg", Material.PILLAGER_SPAWN_EGG));
        registered.add(new BaseItem("Ravager Spawn Egg", Material.RAVAGER_SPAWN_EGG));
        registered.add(new BaseItem("Scute", Material.SCUTE));
        registered.add(new BaseItem("Sea Grass", Material.SEAGRASS));
        registered.add(new BaseItem("Sea Pickle", Material.SEA_PICKLE));
        registered.add(new BaseItem("Shulker Box", Material.SHULKER_BOX));
        registered.add(new BaseItem("Smooth Quartz", Material.SMOOTH_QUARTZ));
        registered.add(new BaseItem("Smooth Stone", Material.SMOOTH_STONE));
        registered.add(new BaseItem("TNT Minecart", Material.TNT_MINECART));
        registered.add(new BaseItem("Trident", Material.TRIDENT));
        registered.add(new BaseItem("Tropical Fish Bucket", Material.TROPICAL_FISH_BUCKET));
        registered.add(new BaseItem("Tropical Fish Spawn Egg", Material.TROPICAL_FISH_SPAWN_EGG));
        registered.add(new BaseItem("Tube Coral", Material.TUBE_CORAL));
        registered.add(new BaseItem("Tube Coral Block", Material.TUBE_CORAL_BLOCK));
        registered.add(new BaseItem("Tube Coral Fan", Material.TUBE_CORAL_FAN));
        registered.add(new BaseItem("Turtle Egg", Material.TURTLE_EGG));
        registered.add(new BaseItem("Turtle Helmet", Material.TURTLE_HELMET));
        registered.add(new BaseItem("Turtle Spawn Egg", Material.TURTLE_SPAWN_EGG));
        registered.add(new BaseItem("Wood Pickaxe", Material.WOODEN_PICKAXE));
        registered.add(new BaseItem("Wood Shovel", Material.WOODEN_SHOVEL));

        registered.add(new BaseItem("Potion", Material.POTION, new PotionData(PotionType.WATER, false, false)));
        registered.add(new BaseItem("Awkward Potion", Material.POTION, new PotionData(PotionType.AWKWARD, false, false)));
        registered.add(new BaseItem("Thick Potion", Material.POTION, new PotionData(PotionType.THICK, false, false)));
        registered.add(new BaseItem("Mundane Potion", Material.POTION, new PotionData(PotionType.MUNDANE, false, false)));
        registered.add(new BaseItem("Potion of Regeneration", Material.POTION, new PotionData(PotionType.REGEN, false, false)));
        registered.add(new BaseItem("Potion of Regeneration (Extended)", Material.POTION, new PotionData(PotionType.REGEN, true, false)));
        registered.add(new BaseItem("Potion of Regeneration II", Material.POTION, new PotionData(PotionType.REGEN, false, true)));
        registered.add(new BaseItem("Potion of Swiftness", Material.POTION, new PotionData(PotionType.SPEED, false, false)));
        registered.add(new BaseItem("Potion of Swiftness (Extended)", Material.POTION, new PotionData(PotionType.SPEED, true, false)));
        registered.add(new BaseItem("Potion of Swiftness II", Material.POTION, new PotionData(PotionType.SPEED, false, true)));
        registered.add(new BaseItem("Potion of Fire Resistance", Material.POTION, new PotionData(PotionType.FIRE_RESISTANCE, false, false)));
        registered.add(new BaseItem("Potion of Fire Resistance (Extended)", Material.POTION, new PotionData(PotionType.FIRE_RESISTANCE, true, false)));
        registered.add(new BaseItem("Potion of Healing", Material.POTION, new PotionData(PotionType.INSTANT_HEAL, false, false)));
        registered.add(new BaseItem("Potion of Healing II", Material.POTION, new PotionData(PotionType.INSTANT_HEAL, false, true)));
        registered.add(new BaseItem("Potion of Night Vision", Material.POTION, new PotionData(PotionType.NIGHT_VISION, false, false)));
        registered.add(new BaseItem("Potion of Night Vision (Extended)", Material.POTION, new PotionData(PotionType.NIGHT_VISION, true, false)));
        registered.add(new BaseItem("Potion of Strength", Material.POTION, new PotionData(PotionType.STRENGTH, false, false)));
        registered.add(new BaseItem("Potion of Strength (Extended)", Material.POTION, new PotionData(PotionType.STRENGTH, true, false)));
        registered.add(new BaseItem("Potion of Strength II", Material.POTION, new PotionData(PotionType.STRENGTH, false, true)));
        registered.add(new BaseItem("Potion of Poison", Material.POTION, new PotionData(PotionType.POISON, false, false)));
        registered.add(new BaseItem("Potion of Poison (Extended)", Material.POTION, new PotionData(PotionType.POISON, true, false)));
        registered.add(new BaseItem("Potion of Poison II", Material.POTION, new PotionData(PotionType.POISON, false, true)));
        registered.add(new BaseItem("Potion of Weakness", Material.POTION, new PotionData(PotionType.WEAKNESS, false, false)));
        registered.add(new BaseItem("Potion of Weakness (Extended)", Material.POTION, new PotionData(PotionType.WEAKNESS, true, false)));
        registered.add(new BaseItem("Potion of Slowness", Material.POTION, new PotionData(PotionType.SLOWNESS, false, false)));
        registered.add(new BaseItem("Potion of Slowness (Extended)", Material.POTION, new PotionData(PotionType.SLOWNESS, true, false)));
        registered.add(new BaseItem("Potion of Harming", Material.POTION, new PotionData(PotionType.INSTANT_DAMAGE, false, false)));
        registered.add(new BaseItem("Potion of Harming II", Material.POTION, new PotionData(PotionType.INSTANT_DAMAGE, false, true)));

        registered.add(new BaseItem("Splash Potion", Material.SPLASH_POTION));
        registered.add(new BaseItem("Splash Mundane Potion", Material.SPLASH_POTION, new PotionData(PotionType.MUNDANE, false, false)));
        registered.add(new BaseItem("Lingering Potion", Material.LINGERING_POTION));
        registered.add(new BaseItem("Splash Potion of Regeneration", Material.SPLASH_POTION, new PotionData(PotionType.REGEN, false, false)));
        registered.add(new BaseItem("Splash Potion of Regeneration (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.REGEN, true, false)));
        registered.add(new BaseItem("Splash Potion of Regeneration II", Material.SPLASH_POTION, new PotionData(PotionType.REGEN, false, true)));
        registered.add(new BaseItem("Splash Potion of Swiftness", Material.SPLASH_POTION, new PotionData(PotionType.SPEED, false, false)));
        registered.add(new BaseItem("Splash Potion of Swiftness (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.SPEED, true, false)));
        registered.add(new BaseItem("Splash Potion of Swiftness II", Material.SPLASH_POTION, new PotionData(PotionType.SPEED, false, true)));
        registered.add(new BaseItem("Splash Potion of Fire Resistance", Material.SPLASH_POTION, new PotionData(PotionType.FIRE_RESISTANCE, false, false)));
        registered.add(new BaseItem("Splash Potion of Fire Resistance (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.FIRE_RESISTANCE, true, false)));
        registered.add(new BaseItem("Splash Potion of Healing", Material.SPLASH_POTION, new PotionData(PotionType.INSTANT_HEAL, false, false)));
        registered.add(new BaseItem("Splash Potion of Healing II", Material.SPLASH_POTION, new PotionData(PotionType.INSTANT_HEAL, false, true)));
        registered.add(new BaseItem("Splash Potion of Strength", Material.SPLASH_POTION, new PotionData(PotionType.STRENGTH, false, false)));
        registered.add(new BaseItem("Splash Potion of Strength (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.STRENGTH, true, false)));
        registered.add(new BaseItem("Splash Potion of Strength II", Material.SPLASH_POTION, new PotionData(PotionType.STRENGTH, false, true)));
        registered.add(new BaseItem("Splash Potion of Poison", Material.SPLASH_POTION, new PotionData(PotionType.POISON, false, false)));
        registered.add(new BaseItem("Splash Potion of Poison (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.POISON, true, false)));
        registered.add(new BaseItem("Splash Potion of Poison II", Material.SPLASH_POTION, new PotionData(PotionType.POISON, false, true)));
        registered.add(new BaseItem("Splash Potion of Weakness", Material.SPLASH_POTION, new PotionData(PotionType.WEAKNESS, false, false)));
        registered.add(new BaseItem("Splash Potion of Weakness (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.WEAKNESS, true, false)));
        registered.add(new BaseItem("Splash Potion of Slowness", Material.SPLASH_POTION, new PotionData(PotionType.SLOWNESS, false, false)));
        registered.add(new BaseItem("Splash Potion of Slowness (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.SLOWNESS, true, false)));
        registered.add(new BaseItem("Splash Potion of Water Breathing", Material.SPLASH_POTION, new PotionData(PotionType.WATER_BREATHING, false, false)));
        registered.add(new BaseItem("Splash Potion of Water Breathing (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.WATER_BREATHING, true, false)));
        registered.add(new BaseItem("Splash Potion of Leaping", Material.SPLASH_POTION, new PotionData(PotionType.JUMP, false, false)));
        registered.add(new BaseItem("Splash Potion of Leaping (Extended)", Material.SPLASH_POTION, new PotionData(PotionType.JUMP, true, false)));
        registered.add(new BaseItem("Splash Potion of Leaping II", Material.SPLASH_POTION, new PotionData(PotionType.JUMP, false, true)));
    }

    public static Optional<BaseItem> find(String name) {
        return registered.stream().filter(item -> item.getName().equalsIgnoreCase(name)).findFirst();
    }
}
